package co.touchlab.skie.plugin.libraries.dependencies.swift

object ExpectedMissingSymbolsProvider {

    val missingSymbols = listOf(
        // Bugsnag
        "_OBJC_CLASS_\$_Bugsnag",
        "_OBJC_CLASS_\$_BugsnagError",
        "_OBJC_CLASS_\$_BugsnagFeatureFlag",
        "_OBJC_CLASS_\$_BugsnagStackframe",
        "_OBJC_CLASS_\$_BugsnagHandledState",

        // Firebase
        "_OBJC_CLASS_\$_FIRActionCodeInfo",
        "_OBJC_CLASS_\$_FIRActionCodeSettings",
        "_OBJC_CLASS_\$_FIRAnalytics",
        "_OBJC_CLASS_\$_FIRApp",
        "_OBJC_CLASS_\$_FIRAuth",
        "_OBJC_CLASS_\$_FIRAuthCredential",
        "_OBJC_CLASS_\$_FIRAuthDataResult",
        "_OBJC_CLASS_\$_FIRAuthSettings",
        "_OBJC_CLASS_\$_FIRAuthTokenResult",
        "_OBJC_CLASS_\$_FIRCrashlytics",
        "_OBJC_CLASS_\$_FIRDataSnapshot",
        "_OBJC_CLASS_\$_FIRDatabase",
        "_OBJC_CLASS_\$_FIRDocumentChange",
        "_OBJC_CLASS_\$_FIRDocumentSnapshot",
        "_OBJC_CLASS_\$_FIREmailAuthProvider",
        "_OBJC_CLASS_\$_FIRExceptionModel",
        "_OBJC_CLASS_\$_FIRFacebookAuthProvider",
        "_OBJC_CLASS_\$_FIRFieldPath",
        "_OBJC_CLASS_\$_FIRFieldValue",
        "_OBJC_CLASS_\$_FIRFirestore",
        "_OBJC_CLASS_\$_FIRFirestoreSettings",
        "_OBJC_CLASS_\$_FIRFunctions",
        "_OBJC_CLASS_\$_FIRGitHubAuthProvider",
        "_OBJC_CLASS_\$_FIRGoogleAuthProvider",
        "_OBJC_CLASS_\$_FIRHTTPSCallableResult",
        "_OBJC_CLASS_\$_FIRInstallations",
        "_OBJC_CLASS_\$_FIRInstallationsAuthTokenResult",
        "_OBJC_CLASS_\$_FIRMessaging",
        "_OBJC_CLASS_\$_FIRMemoryCacheSettings",
        "_OBJC_CLASS_\$_FIRMemoryEagerGCSettings",
        "_OBJC_CLASS_\$_FIRMemoryLRUGCSettings",
        "_OBJC_CLASS_\$_FIRMultiFactorInfo",
        "_OBJC_CLASS_\$_FIRMultiFactorSession",
        "_OBJC_CLASS_\$_FIROAuthProvider",
        "_OBJC_CLASS_\$_FIROptions",
        "_OBJC_CLASS_\$_FIRPerformance",
        "_OBJC_CLASS_\$_FIRPersistentCacheSettings",
        "_OBJC_CLASS_\$_FIRPhoneAuthProvider",
        "_OBJC_CLASS_\$_FIRRemoteConfig",
        "_OBJC_CLASS_\$_FIRRemoteConfigSettings",
        "_OBJC_CLASS_\$_FIRServerValue",
        "_OBJC_CLASS_\$_FIRStackFrame",
        "_OBJC_CLASS_\$_FIRStorage",
        "_OBJC_CLASS_\$_FIRStorageMetadata",
        "_OBJC_CLASS_\$_FIRStorageReference",
        "_OBJC_CLASS_\$_FIRQuerySnapshot",
        "_OBJC_CLASS_\$_FIRTimestamp",
        "_OBJC_CLASS_\$_FIRTransactionResult",
        "_OBJC_CLASS_\$_FIRTwitterAuthProvider",
        "_OBJC_CLASS_\$_FIRUser",
        "_OBJC_CLASS_\$_FIRDocumentReference",
        "_OBJC_CLASS_\$_FIRGeoPoint",
        "_FIRAuthErrorDomain",
        "_FIRCLSExceptionRecordNSException",
        "_FIRFirestoreErrorDomain",
        "_FIRRemoteConfigErrorDomain",
        "_OBJC_CLASS_\$__TtC16MCRCDynamicProxy20FirebaseDynamicProxy",
        "_OBJC_CLASS_\$_FIRFilter",
        "_OBJC_CLASS_\$__TtC18kfirebaseFirestore18KFirebaseFirestore",
        "_OBJC_CLASS_\$__TtC9kmmcrypto16IOSCryptoManager",
        "_OBJC_CLASS_\$__TtC20KFirebaseAuthInterop15AuthCredentials",
        "_OBJC_CLASS_\$__TtC16KIOSNotification16KIOSNotification",
        "_OBJC_CLASS_\$__TtC20KFirebaseAuthInterop20KFirebaseAuthInterop",

        // CouchbaseLite
        "_OBJC_CLASS_\$_CBLArray",
        "_OBJC_CLASS_\$_CBLBlob",
        "_OBJC_CLASS_\$_CBLCollectionConfiguration",
        "_OBJC_CLASS_\$_CBLDictionary",
        "_OBJC_CLASS_\$_CBLFullTextIndexConfiguration",
        "_OBJC_CLASS_\$_CBLLogFileConfiguration",
        "_OBJC_CLASS_\$_CBLMessageEndpointListenerConfiguration",
        "_OBJC_CLASS_\$_CBLMutableArray",
        "_OBJC_CLASS_\$_CBLMutableDictionary",
        "_OBJC_CLASS_\$_CBLQueryParameters",
        "_OBJC_CLASS_\$_CBLReplicatorConfiguration",
        "_OBJC_CLASS_\$_CBLTLSIdentity",
        "_OBJC_CLASS_\$_CBLURLEndpointListenerConfiguration",
        "_OBJC_CLASS_\$_CBLValueIndexConfiguration",
        "_OBJC_CLASS_\$_CBLCollection",
        "_OBJC_CLASS_\$_CBLDatabase",
        "_OBJC_CLASS_\$_CBLDatabaseConfiguration",
        "_OBJC_CLASS_\$_CBLMutableDocument",
        "_OBJC_CLASS_\$_CBLQueryBuilder",
        "_OBJC_CLASS_\$_CBLQueryDataSource",
        "_OBJC_CLASS_\$_CBLQueryExpression",
        "_OBJC_CLASS_\$_CBLQueryResult",
        "_OBJC_CLASS_\$_CBLQuerySelectResult",
        "_OBJC_CLASS_\$_CBLScope",
        "_OBJC_CLASS_\$_CBLBasicAuthenticator",
        "_OBJC_CLASS_\$_CBLClientCertificateAuthenticator",
        "_OBJC_CLASS_\$_CBLDatabaseEndpoint",
        "_OBJC_CLASS_\$_CBLEncryptionKey",
        "_OBJC_CLASS_\$_CBLFullTextIndexItem",
        "_OBJC_CLASS_\$_CBLIndexBuilder",
        "_OBJC_CLASS_\$_CBLListenerCertificateAuthenticator",
        "_OBJC_CLASS_\$_CBLListenerPasswordAuthenticator",
        "_OBJC_CLASS_\$_CBLMessage",
        "_OBJC_CLASS_\$_CBLMessageEndpoint",
        "_OBJC_CLASS_\$_CBLMessageEndpointListener",
        "_OBJC_CLASS_\$_CBLMessagingError",
        "_OBJC_CLASS_\$_CBLQueryArrayExpression",
        "_OBJC_CLASS_\$_CBLQueryArrayFunction",
        "_OBJC_CLASS_\$_CBLQueryCollation",
        "_OBJC_CLASS_\$_CBLQueryFullTextFunction",
        "_OBJC_CLASS_\$_CBLQueryFunction",
        "_OBJC_CLASS_\$_CBLQueryJoin",
        "_OBJC_CLASS_\$_CBLQueryLimit",
        "_OBJC_CLASS_\$_CBLQueryOrdering",
        "_OBJC_CLASS_\$_CBLReplicator",
        "_OBJC_CLASS_\$_CBLSessionAuthenticator",
        "_OBJC_CLASS_\$_CBLURLEndpoint",
        "_OBJC_CLASS_\$_CBLURLEndpointListener",
        "_OBJC_CLASS_\$_CBLValueIndexItem",
        "_OBJC_CLASS_\$_CBLQuery",

        // DyteWebRTC
        "_OBJC_CLASS_\$_DyteRTCAudioTrack",
        "_OBJC_CLASS_\$_DyteRTCCameraVideoCapturer",
        "_OBJC_CLASS_\$_DyteRTCCertificate",
        "_OBJC_CLASS_\$_DyteRTCConfiguration",
        "_OBJC_CLASS_\$_DyteRTCDataBuffer",
        "_OBJC_CLASS_\$_DyteRTCDataChannelConfiguration",
        "_OBJC_CLASS_\$_DyteRTCDefaultVideoDecoderFactory",
        "_OBJC_CLASS_\$_DyteRTCDefaultVideoEncoderFactory",
        "_OBJC_CLASS_\$_DyteRTCIceCandidate",
        "_OBJC_CLASS_\$_DyteRTCIceServer",
        "_OBJC_CLASS_\$_DyteRTCMediaConstraints",
        "_OBJC_CLASS_\$_DyteRTCMediaStream",
        "_OBJC_CLASS_\$_DyteRTCPeerConnectionFactory",
        "_OBJC_CLASS_\$_DyteRTCRtpCodecParameters",
        "_OBJC_CLASS_\$_DyteRTCRtpEncodingParameters",
        "_OBJC_CLASS_\$_DyteRTCRtpHeaderExtension",
        "_OBJC_CLASS_\$_DyteRTCRtpReceiver",
        "_OBJC_CLASS_\$_DyteRTCRtpSender",
        "_OBJC_CLASS_\$_DyteRTCRtpTransceiver",
        "_OBJC_CLASS_\$_DyteRTCRtpTransceiverInit",
        "_OBJC_CLASS_\$_DyteRTCSessionDescription",
        "_OBJC_CLASS_\$_DyteRTCVideoTrack",
        "_OBJC_CLASS_\$_DyteRTCCVPixelBuffer",
        "_OBJC_CLASS_\$_DyteRTCMTLVideoView",
        "_OBJC_CLASS_\$_DyteRTCVideoCapturer",
        "_OBJC_CLASS_\$_DyteRTCVideoFrame",
        "_OBJC_CLASS_\$_DyteRTCDefaultAudioProcessingModule",

        // AWSCore
        "_OBJC_CLASS_\$_AWSEndpoint",
        "_OBJC_CLASS_\$_AWSServiceConfiguration",
        "_OBJC_CLASS_\$_AWSServiceManager",
        "_OBJC_CLASS_\$_AWSStaticCredentialsProvider",
        "_OBJC_CLASS_\$_AWSRequest",

        // AWSS3
        "_OBJC_CLASS_\$_AWSS3",
        "_OBJC_CLASS_\$_AWSS3CreateBucketOutput",
        "_OBJC_CLASS_\$_AWSS3CreateBucketRequest",
        "_OBJC_CLASS_\$_AWSS3DeleteBucketRequest",
        "_OBJC_CLASS_\$_AWSS3DeleteObjectsOutput",
        "_OBJC_CLASS_\$_AWSS3DeleteObjectsRequest",
        "_OBJC_CLASS_\$_AWSS3GetPreSignedURLRequest",
        "_OBJC_CLASS_\$_AWSS3ListBucketsOutput",
        "_OBJC_CLASS_\$_AWSS3ListObjectsV2Output",
        "_OBJC_CLASS_\$_AWSS3ListObjectsV2Request",
        "_OBJC_CLASS_\$_AWSS3PreSignedURLBuilder",
        "_OBJC_CLASS_\$_AWSS3PutObjectOutput",
        "_OBJC_CLASS_\$_AWSS3PutObjectRequest",
        "_OBJC_CLASS_\$_AWSS3Remove",
        "_OBJC_CLASS_\$_AWSS3TransferUtility",
        "_OBJC_CLASS_\$_AWSS3TransferUtilityUploadExpression",
        "_OBJC_CLASS_\$_AWSS3TransferUtilityUploadTask",

        // AWSDynamoDB
        "_AWSDynamoDBErrorDomain",
        "_OBJC_CLASS_\$_AWSDynamoDB",
        "_OBJC_CLASS_\$_AWSDynamoDBAttributeDefinition",
        "_OBJC_CLASS_\$_AWSDynamoDBAttributeValue",
        "_OBJC_CLASS_\$_AWSDynamoDBAttributeValueUpdate",
        "_OBJC_CLASS_\$_AWSDynamoDBCreateTableInput",
        "_OBJC_CLASS_\$_AWSDynamoDBCreateTableOutput",
        "_OBJC_CLASS_\$_AWSDynamoDBDeleteItemInput",
        "_OBJC_CLASS_\$_AWSDynamoDBDeleteItemOutput",
        "_OBJC_CLASS_\$_AWSDynamoDBDeleteTableInput",
        "_OBJC_CLASS_\$_AWSDynamoDBDeleteTableOutput",
        "_OBJC_CLASS_\$_AWSDynamoDBGetItemInput",
        "_OBJC_CLASS_\$_AWSDynamoDBGetItemOutput",
        "_OBJC_CLASS_\$_AWSDynamoDBKeySchemaElement",
        "_OBJC_CLASS_\$_AWSDynamoDBListTablesInput",
        "_OBJC_CLASS_\$_AWSDynamoDBListTablesOutput",
        "_OBJC_CLASS_\$_AWSDynamoDBProvisionedThroughput",
        "_OBJC_CLASS_\$_AWSDynamoDBPutItemInput",
        "_OBJC_CLASS_\$_AWSDynamoDBPutItemOutput",
        "_OBJC_CLASS_\$_AWSDynamoDBQueryInput",
        "_OBJC_CLASS_\$_AWSDynamoDBQueryOutput",
        "_OBJC_CLASS_\$_AWSDynamoDBScanInput",
        "_OBJC_CLASS_\$_AWSDynamoDBScanOutput",
        "_OBJC_CLASS_\$_AWSDynamoDBUpdateItemInput",
        "_OBJC_CLASS_\$_AWSDynamoDBUpdateItemOutput",

        // AWSCognito
        "_OBJC_CLASS_\$_AWSCognitoCredentialsProvider",

        // GRPCClient
        "_cocoapods_GRPCClient_GRPCDefaultTransportImplList_getter_wrapper5",
        "_OBJC_CLASS_\$_GRPCCall2",
        "_OBJC_CLASS_\$_GRPCMutableCallOptions",
        "_OBJC_CLASS_\$_GRPCRequestOptions",
        "_GRPCDefaultTransportImplList",

        // Protobuf
        "_GPBComputeBoolSize",
        "_OBJC_CLASS_\$_GPBCodedOutputStream",
        "_cocoapods_Protobuf_GPBComputeBoolSize_wrapper53",
        "_cocoapods_Protobuf_GPBComputeBoolSizeNoTag_wrapper73",
        "_cocoapods_Protobuf_GPBComputeDoubleSize_wrapper46",
        "_cocoapods_Protobuf_GPBComputeDoubleSizeNoTag_wrapper66",
        "_cocoapods_Protobuf_GPBComputeEnumSize_wrapper91",
        "_cocoapods_Protobuf_GPBComputeEnumSizeNoTag_wrapper80",
        "_cocoapods_Protobuf_GPBComputeFixed32SizeNoTag_wrapper72",
        "_cocoapods_Protobuf_GPBComputeFixed64SizeNoTag_wrapper71",
        "_cocoapods_Protobuf_GPBComputeFloatSize_wrapper47",
        "_cocoapods_Protobuf_GPBComputeFloatSizeNoTag_wrapper67",
        "_cocoapods_Protobuf_GPBComputeInt32Size_wrapper50",
        "_cocoapods_Protobuf_GPBComputeInt32SizeNoTag_wrapper70",
        "_cocoapods_Protobuf_GPBComputeInt64Size_wrapper49",
        "_cocoapods_Protobuf_GPBComputeInt64SizeNoTag_wrapper69",
        "_cocoapods_Protobuf_GPBComputeRawVarint32Size_wrapper86",
        "_cocoapods_Protobuf_GPBComputeSFixed32SizeNoTag_wrapper81",
        "_cocoapods_Protobuf_GPBComputeSFixed64SizeNoTag_wrapper82",
        "_cocoapods_Protobuf_GPBComputeSInt32SizeNoTag_wrapper83",
        "_cocoapods_Protobuf_GPBComputeSInt64SizeNoTag_wrapper84",
        "_cocoapods_Protobuf_GPBComputeStringSize_wrapper54",
        "_cocoapods_Protobuf_GPBComputeStringSizeNoTag_wrapper74",
        "_cocoapods_Protobuf_GPBComputeTagSize_wrapper64",
        "_cocoapods_Protobuf_GPBComputeUInt32SizeNoTag_wrapper79",
        "_cocoapods_Protobuf_GPBComputeUInt64SizeNoTag_wrapper68",
        "_GPBComputeBoolSizeNoTag",
        "_GPBComputeDoubleSize",
        "_GPBComputeDoubleSizeNoTag",
        "_GPBComputeEnumSize",
        "_GPBComputeEnumSizeNoTag",
        "_GPBComputeFixed32SizeNoTag",
        "_GPBComputeFixed64SizeNoTag",
        "_GPBComputeFloatSize",
        "_GPBComputeFloatSizeNoTag",
        "_GPBComputeInt32Size",
        "_GPBComputeInt32SizeNoTag",
        "_GPBComputeInt64Size",
        "_GPBComputeInt64SizeNoTag",
        "_GPBComputeRawVarint32Size",
        "_GPBComputeSFixed32SizeNoTag",
        "_GPBComputeSFixed64SizeNoTag",
        "_GPBComputeSInt32SizeNoTag",
        "_GPBComputeSInt64SizeNoTag",
        "_GPBComputeStringSize",
        "_GPBComputeStringSizeNoTag",
        "_GPBComputeTagSize",
        "_GPBComputeUInt32SizeNoTag",
        "_GPBComputeUInt64SizeNoTag",

        // RevenueCat
        "_OBJC_CLASS_\$_RCEntitlementInfo",
        "_OBJC_CLASS_\$_RCPurchases",
        "_OBJC_CLASS_\$_RCPaywallViewController",
        "_OBJC_CLASS_\$_RCConfiguration",
        "_OBJC_CLASS_\$_RCDangerousSettings",
        "_OBJC_CLASS_\$_RCOffering",
        "_OBJC_CLASS_\$_RCPackage",
        "_OBJC_CLASS_\$_RCStoreProduct",
        "_OBJC_CLASS_\$_RCStoreProductDiscount",
        "_OBJC_CLASS_\$_RCStoreTransaction",
        "_OBJC_CLASS_\$_RCIntroEligibility",
        "_OBJC_CLASS_\$_RCPurchaseParamsBuilder",
        "_OBJC_CLASS_\$_RCWinBackOffer",
        "_OBJC_CLASS_\$__TtC21PurchasesHybridCommon25IOSAPIAvailabilityChecker",
        "_OBJC_CLASS_\$__TtC23PurchasesHybridCommonUI30CustomerCenterUIViewController",

        "_OBJC_CLASS_\$_GIDConfiguration",
        "_OBJC_CLASS_\$_GIDSignIn",

        "_OBJC_CLASS_\$_GMSCameraPosition",
        "_OBJC_CLASS_\$_GMSCoordinateBounds",
        "_OBJC_CLASS_\$_GMSGeocoder",
        "_OBJC_CLASS_\$_GMSMarker",
        "_OBJC_CLASS_\$_GMSMutablePath",
        "_OBJC_CLASS_\$_GMSPath",
        "_OBJC_CLASS_\$_GMSPolygon",
        "_OBJC_CLASS_\$_GMSPolyline",
        "_kGMSMaxZoomLevel",
        "_kGMSMinZoomLevel",
        "_OBJC_CLASS_\$_GMSAutocompleteFilter",
        "_OBJC_CLASS_\$_GMSAutocompleteSessionToken",
        "_OBJC_CLASS_\$_GMSPlacesClient",
        "_OBJC_CLASS_\$__TtC10KGoogleMap14CameraPosition",

        "_OBJC_CLASS_\$_MGLAnnotationImage",
        "_OBJC_CLASS_\$_MGLLineStyleLayer",
        "_OBJC_CLASS_\$_MGLPointAnnotation",
        "_OBJC_CLASS_\$_MGLPolygonFeature",
        "_OBJC_CLASS_\$_MGLShapeSource",

        "_OBJC_CLASS_\$_MMKV",

        "_OBJC_CLASS_\$__TtC12mokoSocketIo8SocketIo",
        "_OBJC_CLASS_\$__TtC22mokoWidgetsBottomSheet21BottomSheetController",
        "_OBJC_CLASS_\$__TtC21mokoWidgetsCollection22ALCollectionFlowLayout",
        "_OBJC_CLASS_\$__TtC25mokoWidgetsDateTimePicker25DateBottomSheetController",
        "_OBJC_CLASS_\$__TtC23mokoWidgetsImageNetwork12ImageNetwork",

        "_OBJC_CLASS_\$_MPEvent",
        "_OBJC_CLASS_\$_MParticle",

        "_OBJC_CLASS_\$_JFBCrypt",
        "_OBJC_CLASS_\$_OIDAuthState",
        "_OBJC_CLASS_\$_OIDAuthorizationRequest",
        "_OBJC_CLASS_\$_OIDAuthorizationResponse",
        "_OBJC_CLASS_\$_OIDAuthorizationService",
        "_OBJC_CLASS_\$_OIDEndSessionRequest",
        "_OBJC_CLASS_\$_OIDEndSessionResponse",
        "_OBJC_CLASS_\$_OIDExternalUserAgentIOS",
        "_OBJC_CLASS_\$_OIDServiceConfiguration",
        "_OBJC_CLASS_\$_OIDTokenRequest",
        "_OBJC_CLASS_\$_OIDTokenResponse",
        "_OBJC_CLASS_\$_OIDURLQueryComponent",
        "_OIDGeneralErrorDomain",
        "_OIDGrantTypeAuthorizationCode",
        "_OIDResponseTypeCode",
        "_OIDScopeEmail",
        "_OIDOAuthAuthorizationErrorDomain",
        "_OIDOAuthErrorFieldErrorDescription",
        "_OIDOAuthErrorResponseErrorKey",
        "_OIDOAuthTokenErrorDomain",
        "_secp256k1_context_create",
        "_secp256k1_context_destroy",
        "_secp256k1_ec_seckey_verify",
        "_secp256k1_ecdsa_sign",
        "_secp256k1_ecdsa_signature_serialize_compact",

        "_olm_account",
        "_olm_account_fallback_key",
        "_olm_account_fallback_key_length",
        "_olm_account_generate_fallback_key",
        "_olm_account_generate_fallback_key_random_length",
        "_olm_account_generate_one_time_keys",
        "_olm_account_generate_one_time_keys_random_length",
        "_olm_account_identity_keys",
        "_olm_account_identity_keys_length",
        "_olm_account_last_error",
        "_olm_account_mark_keys_as_published",
        "_olm_account_max_number_of_one_time_keys",
        "_olm_account_one_time_keys",
        "_olm_account_one_time_keys_length",
        "_olm_account_sign",
        "_olm_account_signature_length",
        "_olm_account_size",
        "_olm_clear_account",
        "_olm_clear_inbound_group_session",
        "_olm_clear_outbound_group_session",
        "_olm_clear_pk_decryption",
        "_olm_clear_pk_encryption",
        "_olm_clear_pk_signing",
        "_olm_clear_sas",
        "_olm_clear_session",
        "_olm_clear_utility",
        "_olm_create_account",
        "_olm_create_account_random_length",
        "_olm_create_inbound_session",
        "_olm_create_inbound_session_from",
        "_olm_create_outbound_session",
        "_olm_create_outbound_session_random_length",
        "_olm_create_sas",
        "_olm_create_sas_random_length",
        "_olm_decrypt",
        "_olm_decrypt_max_plaintext_length",
        "_olm_ed25519_verify",
        "_olm_encrypt",
        "_olm_encrypt_message_length",
        "_olm_encrypt_message_type",
        "_olm_encrypt_random_length",
        "_olm_error",
        "_olm_export_inbound_group_session",
        "_olm_export_inbound_group_session_length",
        "_olm_group_decrypt",
        "_olm_group_decrypt_max_plaintext_length",
        "_olm_group_encrypt",
        "_olm_group_encrypt_message_length",
        "_olm_import_inbound_group_session",
        "_olm_inbound_group_session",
        "_olm_inbound_group_session_first_known_index",
        "_olm_inbound_group_session_id",
        "_olm_inbound_group_session_id_length",
        "_olm_inbound_group_session_is_verified",
        "_olm_inbound_group_session_last_error",
        "_olm_inbound_group_session_size",
        "_olm_init_inbound_group_session",
        "_olm_init_outbound_group_session",
        "_olm_init_outbound_group_session_random_length",
        "_olm_matches_inbound_session",
        "_olm_matches_inbound_session_from",
        "_olm_outbound_group_session",
        "_olm_outbound_group_session_id",
        "_olm_outbound_group_session_id_length",
        "_olm_outbound_group_session_key",
        "_olm_outbound_group_session_key_length",
        "_olm_outbound_group_session_last_error",
        "_olm_outbound_group_session_message_index",
        "_olm_outbound_group_session_size",
        "_olm_pickle_account",
        "_olm_pickle_account_length",
        "_olm_pickle_inbound_group_session",
        "_olm_pickle_inbound_group_session_length",
        "_olm_pickle_outbound_group_session",
        "_olm_pickle_outbound_group_session_length",
        "_olm_pickle_pk_decryption",
        "_olm_pickle_pk_decryption_length",
        "_olm_pickle_session",
        "_olm_pickle_session_length",
        "_olm_pk_ciphertext_length",
        "_olm_pk_decrypt",
        "_olm_pk_decryption",
        "_olm_pk_decryption_last_error",
        "_olm_pk_decryption_size",
        "_olm_pk_encrypt",
        "_olm_pk_encrypt_random_length",
        "_olm_pk_encryption",
        "_olm_pk_encryption_last_error",
        "_olm_pk_encryption_set_recipient_key",
        "_olm_pk_encryption_size",
        "_olm_pk_get_private_key",
        "_olm_pk_key_from_private",
        "_olm_pk_key_length",
        "_olm_pk_mac_length",
        "_olm_pk_max_plaintext_length",
        "_olm_pk_private_key_length",
        "_olm_pk_sign",
        "_olm_pk_signature_length",
        "_olm_pk_signing",
        "_olm_pk_signing_key_from_seed",
        "_olm_pk_signing_last_error",
        "_olm_pk_signing_public_key_length",
        "_olm_pk_signing_seed_length",
        "_olm_pk_signing_size",
        "_olm_remove_one_time_keys",
        "_olm_sas",
        "_olm_sas_calculate_mac",
        "_olm_sas_calculate_mac_long_kdf",
        "_olm_sas_generate_bytes",
        "_olm_sas_get_pubkey",
        "_olm_sas_is_their_key_set",
        "_olm_sas_last_error",
        "_olm_sas_mac_length",
        "_olm_sas_pubkey_length",
        "_olm_sas_set_their_key",
        "_olm_sas_size",
        "_olm_session",
        "_olm_session_describe",
        "_olm_session_has_received_message",
        "_olm_session_id",
        "_olm_session_id_length",
        "_olm_session_last_error",
        "_olm_session_size",
        "_olm_sha256",
        "_olm_sha256_length",
        "_olm_unpickle_account",
        "_olm_unpickle_inbound_group_session",
        "_olm_unpickle_outbound_group_session",
        "_olm_unpickle_pk_decryption",
        "_olm_unpickle_session",
        "_olm_utility",
        "_olm_utility_last_error",
        "_olm_utility_size",

        "_OBJC_CLASS_\$_PSYMarsXLog",

        "_OBJC_CLASS_\$_Reachability",

        "_OBJC_CLASS_\$_RTCAudioTrack",
        "_OBJC_CLASS_\$_RTCCameraVideoCapturer",
        "_OBJC_CLASS_\$_RTCCertificate",
        "_OBJC_CLASS_\$_RTCConfiguration",
        "_OBJC_CLASS_\$_RTCDataBuffer",
        "_OBJC_CLASS_\$_RTCDataChannelConfiguration",
        "_OBJC_CLASS_\$_RTCDefaultVideoDecoderFactory",
        "_OBJC_CLASS_\$_RTCDefaultVideoEncoderFactory",
        "_OBJC_CLASS_\$_RTCIceCandidate",
        "_OBJC_CLASS_\$_RTCIceServer",
        "_OBJC_CLASS_\$_RTCMediaConstraints",
        "_OBJC_CLASS_\$_RTCMediaStream",
        "_OBJC_CLASS_\$_RTCPeerConnectionFactory",
        "_OBJC_CLASS_\$_RTCRtpCodecParameters",
        "_OBJC_CLASS_\$_RTCRtpEncodingParameters",
        "_OBJC_CLASS_\$_RTCRtpHeaderExtension",
        "_OBJC_CLASS_\$_RTCRtpReceiver",
        "_OBJC_CLASS_\$_RTCRtpSender",
        "_OBJC_CLASS_\$_RTCRtpTransceiver",
        "_OBJC_CLASS_\$_RTCRtpTransceiverInit",
        "_OBJC_CLASS_\$_RTCSessionDescription",
        "_OBJC_CLASS_\$_RTCVideoTrack",
        "_RTCCleanupSSL",
        "_RTCInitFieldTrialDictionary",
        "_RTCInitializeSSL",
        "_RTCSetMinDebugLogLevel",
        "_RTCSetupInternalTracer",
        "_RTCShutdownInternalTracer",
        "_kRTCMediaStreamTrackKindAudio",
        "_kRTCMediaStreamTrackKindVideo",

        "_OBJC_CLASS_\$_SEGAnalytics",
        "_OBJC_CLASS_\$_SEGAnalyticsConfiguration",

        "_OBJC_CLASS_\$_PrivateSentrySDKOnly",
        "_OBJC_CLASS_\$_SentryAttachment",
        "_OBJC_CLASS_\$_SentryBreadcrumb",
        "_OBJC_CLASS_\$_SentryDependencyContainer",
        "_OBJC_CLASS_\$_SentryEnvelope",
        "_OBJC_CLASS_\$_SentryEnvelopeHeader",
        "_OBJC_CLASS_\$_SentryEnvelopeItem",
        "_OBJC_CLASS_\$_SentryEvent",
        "_OBJC_CLASS_\$_SentryException",
        "_OBJC_CLASS_\$_SentryHttpStatusCodeRange",
        "_OBJC_CLASS_\$_SentryId",
        "_OBJC_CLASS_\$__TtC6Sentry8SentryId",
        "_OBJC_CLASS_\$_SentryMechanism",
        "_OBJC_CLASS_\$_SentryMessage",
        "_OBJC_CLASS_\$_SentryScope",
        "_OBJC_CLASS_\$_SentrySDK",
        "_OBJC_CLASS_\$_SentryUser",
        "_OBJC_CLASS_\$_SentryUserFeedback",
        "_OBJC_CLASS_\$_SentryStacktrace",
        "_OBJC_CLASS_\$__TtC6Sentry19SentryReplayOptions",
        "_sentrycrash_async_backtrace_decref",
        "_sentrycrashsc_initWithBacktrace",

        "_OBJC_CLASS_\$__TtC13SocketWrapper19ClientSocketWrapper",
        "_OBJC_CLASS_\$__TtC13SocketWrapper27ServerSocketListenerWrapper",

        "_OBJC_CLASS_\$_SSZipArchive",

        "_OBJC_CLASS_\$_IValueWrapper",
        "_OBJC_CLASS_\$_Tensor",
        "_OBJC_CLASS_\$_TorchModule",

        // app.cash.molecule:molecule-runtime-iosarm64:0.7.0
        "_kfun:app.cash.molecule#launchMolecule__at__kotlinx.coroutines.CoroutineScope(app.cash.molecule.RecompositionClock;kotlin.Function0<0:0>){0§<kotlin.Any?>}kotlinx.coroutines.flow.StateFlow<0:0>",
        "_kfun:app.cash.molecule#launchMolecule__at__kotlinx.coroutines.CoroutineScope(app.cash.molecule.RecompositionClock;kotlin.Function1<0:0,kotlin.Unit>;kotlin.Function0<0:0>){0§<kotlin.Any?>}",
        "_kfun:app.cash.molecule#moleculeFlow(app.cash.molecule.RecompositionClock;kotlin.Function0<0:0>){0§<kotlin.Any?>}kotlinx.coroutines.flow.Flow<0:0>",

        // app.cash.redwood:redwood-layout-compose-iosarm64:0.2.1
        "_kfun:app.cash.redwood.layout.compose#Column(app.cash.redwood.layout.api.Constraint;app.cash.redwood.layout.api.Constraint;app.cash.redwood.layout.api.Padding;app.cash.redwood.layout.api.Overflow;app.cash.redwood.layout.api.CrossAxisAlignment;app.cash.redwood.layout.api.MainAxisAlignment;app.cash.redwood.LayoutModifier;kotlin.Function1<app.cash.redwood.layout.compose.ColumnScope,kotlin.Unit>){}",
        "_kfun:app.cash.redwood.layout.compose#Row(app.cash.redwood.layout.api.Constraint;app.cash.redwood.layout.api.Constraint;app.cash.redwood.layout.api.Padding;app.cash.redwood.layout.api.Overflow;app.cash.redwood.layout.api.MainAxisAlignment;app.cash.redwood.layout.api.CrossAxisAlignment;app.cash.redwood.LayoutModifier;kotlin.Function1<app.cash.redwood.layout.compose.RowScope,kotlin.Unit>){}",

        // app.cash.redwood:redwood-treehouse-lazylayout-compose-iosarm64:0.2.1
        "_kfun:app.cash.redwood.treehouse.lazylayout.compose#LazyColumn(kotlin.collections.List<app.cash.redwood.treehouse.lazylayout.api.LazyListIntervalContent>;app.cash.redwood.LayoutModifier){}",
        "_kfun:app.cash.redwood.treehouse.lazylayout.compose#LazyColumn__Skie_DefaultArguments__123(kotlin.collections.List<app.cash.redwood.treehouse.lazylayout.api.LazyListIntervalContent>){}",

        // co.touchlab:sqliter-iosarm64:0.7.1
        "_KonanNeedDebugInfo",
        "__Z19RuntimeAssertFailedPKcS0_",
        "__ZN5konan4freeEPv",
        "__ZN5konan6callocEmm",

        // com.adeo:kviewmodel-compose-iosarm64:0.13
        "_kfun:com.adeo.kviewmodel.compose#ViewModel(kotlin.Function0<0:0>;kotlin.Function1<0:0,kotlin.Unit>){0§<com.adeo.kviewmodel.KViewModel>}",
        "_kfun:com.adeo.kviewmodel.compose#observeAsState__at__kotlinx.coroutines.flow.SharedFlow<0:0>(kotlin.coroutines.CoroutineContext){0§<kotlin.Any?>}androidx.compose.runtime.State<0:0?>",
        "_kfun:com.adeo.kviewmodel.compose#observeAsState__at__kotlinx.coroutines.flow.StateFlow<0:0>(kotlin.coroutines.CoroutineContext){0§<kotlin.Any?>}androidx.compose.runtime.State<0:0>",

        // com.episode6.redux:compose-ios-arm64:1.0.1
        "_kfun:com.episode6.redux.compose#collectAsState__at__com.episode6.redux.StoreFlow<0:0>(kotlin.coroutines.CoroutineContext){0§<kotlin.Any?>}androidx.compose.runtime.State<0:0>",
        "_kfun:com.episode6.redux.compose#collectAsState__at__com.episode6.redux.StoreFlow<0:0>(kotlin.coroutines.CoroutineContext;kotlin.Function1<0:0,0:1>){0§<kotlin.Any?>;1§<kotlin.Any?>}androidx.compose.runtime.State<0:1>",

        // org.jetbrains.skiko:skiko-iosarm64:0.7.68
        "_org_jetbrains_skia_TextBlobBuilderRunHandler__1nGetFinalizer",
        "_org_jetbrains_skia_TextBlobBuilderRunHandler__1nMake",
        "_org_jetbrains_skia_TextBlobBuilderRunHandler__1nMakeBlob",
        "_org_jetbrains_skia_svg_SVGCanvasKt__1nMake",

        // dev.icerock.moko:resources-compose-iosarm64:0.23.0
        "_OBJC_CLASS_\$_MTLCommandBufferDescriptor",
        "_OBJC_CLASS_\$_MTLCompileOptions",
        "_OBJC_CLASS_\$_MTLDepthStencilDescriptor",
        "_OBJC_CLASS_\$_MTLRenderPassDescriptor",
        "_OBJC_CLASS_\$_MTLRenderPipelineColorAttachmentDescriptor",
        "_OBJC_CLASS_\$_MTLRenderPipelineDescriptor",
        "_OBJC_CLASS_\$_MTLSamplerDescriptor",
        "_OBJC_CLASS_\$_MTLStencilDescriptor",
        "_OBJC_CLASS_\$_MTLTextureDescriptor",
        "_OBJC_CLASS_\$_MTLVertexDescriptor",

        // com.shepeliev:webrtc-kmp-iosarm64:0.114.2
        "_RTCLogEx",

        // dev.icerock.moko:tensorflow-iosarm64:0.2.1
        "_OBJC_CLASS_\$_TFLInterpreter",
        "_OBJC_CLASS_\$_TFLInterpreterOptions",

        // io.github.kkoshin:azure-speech-iosarm64
        "_OBJC_CLASS_\$_SPXAudioConfiguration",
        "_OBJC_CLASS_\$_SPXSpeechConfiguration",
        "_OBJC_CLASS_\$_SPXSpeechRecognizer",
        "_OBJC_CLASS_\$_SPXSpeechSynthesizer",

        "_OBJC_CLASS_\$_TINKAeadConfig",
        "_OBJC_CLASS_\$_TINKAeadFactory",
        "_OBJC_CLASS_\$_TINKAeadKeyTemplate",
        "_OBJC_CLASS_\$_TINKAllConfig",
        "_OBJC_CLASS_\$_TINKBinaryKeysetReader",
        "_OBJC_CLASS_\$_TINKConfig",
        "_OBJC_CLASS_\$_TINKDeterministicAeadConfig",
        "_OBJC_CLASS_\$_TINKDeterministicAeadFactory",
        "_OBJC_CLASS_\$_TINKDeterministicAeadKeyTemplate",
        "_OBJC_CLASS_\$_TINKHybridConfig",
        "_OBJC_CLASS_\$_TINKHybridDecryptFactory",
        "_OBJC_CLASS_\$_TINKHybridEncryptFactory",
        "_OBJC_CLASS_\$_TINKHybridKeyTemplate",
        "_OBJC_CLASS_\$_TINKJSONKeysetReader",
        "_OBJC_CLASS_\$_TINKKeysetHandle",
        "_OBJC_CLASS_\$_TINKMacConfig",
        "_OBJC_CLASS_\$_TINKMacFactory",
        "_OBJC_CLASS_\$_TINKMacKeyTemplate",
        "_OBJC_CLASS_\$_TINKPublicKeySignFactory",
        "_OBJC_CLASS_\$_TINKPublicKeyVerifyFactory",
        "_OBJC_CLASS_\$_TINKSignatureConfig",
        "_OBJC_CLASS_\$_TINKSignatureKeyTemplate",

        "_OBJC_CLASS_\$_CommonDelegate",
        "_OBJC_CLASS_\$_FragmentManager",
        "_OBJC_CLASS_\$_ILGRecyclerViewAdapter",
        "_OBJC_CLASS_\$_ILuaForm",
        "_OBJC_CLASS_\$_ILuaFragment",
        "_OBJC_CLASS_\$_LGAbsListView",
        "_OBJC_CLASS_\$_LGAdapterView",
        "_OBJC_CLASS_\$_LGAutoCompleteTextView",
        "_OBJC_CLASS_\$_LGBottomNavigationView",
        "_OBJC_CLASS_\$_LGButton",
        "_OBJC_CLASS_\$_LGCheckBox",
        "_OBJC_CLASS_\$_LGComboBox",
        "_OBJC_CLASS_\$_LGCompoundButton",
        "_OBJC_CLASS_\$_LGConstraintLayout",
        "_OBJC_CLASS_\$_LGDatePicker",
        "_OBJC_CLASS_\$_LGDrawerLayout",
        "_OBJC_CLASS_\$_LGEditText",
        "_OBJC_CLASS_\$_LGFragmentContainerView",
        "_OBJC_CLASS_\$_LGFragmentStateAdapter",
        "_OBJC_CLASS_\$_LGFrameLayout",
        "_OBJC_CLASS_\$_LGHorizontalScrollView",
        "_OBJC_CLASS_\$_LGImageView",
        "_OBJC_CLASS_\$_LGLinearLayout",
        "_OBJC_CLASS_\$_LGListView",
        "_OBJC_CLASS_\$_LGNavigationView",
        "_OBJC_CLASS_\$_LGProgressBar",
        "_OBJC_CLASS_\$_LGRadioButton",
        "_OBJC_CLASS_\$_LGRadioGroup",
        "_OBJC_CLASS_\$_LGRecyclerView",
        "_OBJC_CLASS_\$_LGRecyclerViewAdapter",
        "_OBJC_CLASS_\$_LGRelativeLayout",
        "_OBJC_CLASS_\$_LGScrollView",
        "_OBJC_CLASS_\$_LGTabLayout",
        "_OBJC_CLASS_\$_LGTextInputEditText",
        "_OBJC_CLASS_\$_LGTextInputLayout",
        "_OBJC_CLASS_\$_LGTextView",
        "_OBJC_CLASS_\$_LGToolbar",
        "_OBJC_CLASS_\$_LGView",
        "_OBJC_CLASS_\$_LGViewGroup",
        "_OBJC_CLASS_\$_LGViewPager",
        "_OBJC_CLASS_\$_LGWebView",
        "_OBJC_CLASS_\$_LuaAppBarConfiguration",
        "_OBJC_CLASS_\$_LuaBuffer",
        "_OBJC_CLASS_\$_LuaBundle",
        "_OBJC_CLASS_\$_LuaColor",
        "_OBJC_CLASS_\$_LuaContext",
        "_OBJC_CLASS_\$_LuaCoroutineScope",
        "_OBJC_CLASS_\$_LuaDatabase",
        "_OBJC_CLASS_\$_LuaDate",
        "_OBJC_CLASS_\$_LuaDefines",
        "_OBJC_CLASS_\$_LuaDialog",
        "_OBJC_CLASS_\$_LuaDispatchers",
        "_OBJC_CLASS_\$_LuaEvent",
        "_OBJC_CLASS_\$_LuaForm",
        "_OBJC_CLASS_\$_LuaFormIntent",
        "_OBJC_CLASS_\$_LuaFragment",
        "_OBJC_CLASS_\$_LuaGraphics",
        "_OBJC_CLASS_\$_LuaHttpClient",
        "_OBJC_CLASS_\$_LuaJSONArray",
        "_OBJC_CLASS_\$_LuaJSONObject",
        "_OBJC_CLASS_\$_LuaJob",
        "_OBJC_CLASS_\$_LuaLifecycle",
        "_OBJC_CLASS_\$_LuaLifecycleObserver",
        "_OBJC_CLASS_\$_LuaLifecycleOwner",
        "_OBJC_CLASS_\$_LuaLiveData",
        "_OBJC_CLASS_\$_LuaLog",
        "_OBJC_CLASS_\$_LuaMenu",
        "_OBJC_CLASS_\$_LuaMutableLiveData",
        "_OBJC_CLASS_\$_LuaNativeCall",
        "_OBJC_CLASS_\$_LuaNativeObject",
        "_OBJC_CLASS_\$_LuaNavController",
        "_OBJC_CLASS_\$_LuaNavHostFragment",
        "_OBJC_CLASS_\$_LuaObjectStore",
        "_OBJC_CLASS_\$_LuaPoint",
        "_OBJC_CLASS_\$_LuaRect",
        "_OBJC_CLASS_\$_LuaRef",
        "_OBJC_CLASS_\$_LuaResource",
        "_OBJC_CLASS_\$_LuaStore",
        "_OBJC_CLASS_\$_LuaStream",
        "_OBJC_CLASS_\$_LuaTab",
        "_OBJC_CLASS_\$_LuaThread",
        "_OBJC_CLASS_\$_LuaToast",
        "_OBJC_CLASS_\$_LuaTranslator",
        "_OBJC_CLASS_\$_LuaViewInflator",
        "_OBJC_CLASS_\$_LuaViewModel",
        "_OBJC_CLASS_\$_LuaViewModelProvider",
        "_OBJC_CLASS_\$_NavOptions",
        "_OBJC_CLASS_\$_NavigationUI",
        "_OBJC_CLASS_\$_ToppingEngine",

        "_BN_bin2bn",
        "_BN_bn2binpad",
        "_BN_free",
        "_BN_num_bits",
        "_ECDSA_SIG_free",
        "_ECDSA_SIG_get0_r",
        "_ECDSA_SIG_get0_s",
        "_ECDSA_SIG_new",
        "_ECDSA_SIG_set0",
        "_EC_GROUP_free",
        "_EC_GROUP_get_curve_name",
        "_EC_GROUP_new_from_params",
        "_ERR_error_string",
        "_ERR_get_error",
        "_EVP_CIPHER_CTX_ctrl",
        "_EVP_CIPHER_CTX_free",
        "_EVP_CIPHER_CTX_get_block_size",
        "_EVP_CIPHER_CTX_new",
        "_EVP_CIPHER_CTX_set_padding",
        "_EVP_CIPHER_fetch",
        "_EVP_CIPHER_free",
        "_EVP_DecryptFinal_ex",
        "_EVP_DecryptInit_ex2",
        "_EVP_DecryptUpdate",
        "_EVP_DigestFinal",
        "_EVP_DigestInit",
        "_EVP_DigestSignFinal",
        "_EVP_DigestSignInit_ex",
        "_EVP_DigestSignUpdate",
        "_EVP_DigestUpdate",
        "_EVP_DigestVerifyFinal",
        "_EVP_DigestVerifyInit_ex",
        "_EVP_DigestVerifyUpdate",
        "_EVP_EncryptFinal_ex",
        "_EVP_EncryptInit_ex2",
        "_EVP_EncryptUpdate",
        "_EVP_MAC_CTX_free",
        "_EVP_MAC_CTX_get_mac_size",
        "_EVP_MAC_CTX_new",
        "_EVP_MAC_fetch",
        "_EVP_MAC_final",
        "_EVP_MAC_free",
        "_EVP_MAC_init",
        "_EVP_MAC_update",
        "_EVP_MD_CTX_free",
        "_EVP_MD_CTX_new",
        "_EVP_MD_fetch",
        "_EVP_MD_free",
        "_EVP_MD_get_block_size",
        "_EVP_MD_get_size",
        "_EVP_PKEY_CTX_free",
        "_EVP_PKEY_CTX_new_from_name",
        "_EVP_PKEY_CTX_new_from_pkey",
        "_EVP_PKEY_CTX_set_params",
        "_EVP_PKEY_decrypt",
        "_EVP_PKEY_decrypt_init_ex",
        "_EVP_PKEY_encrypt",
        "_EVP_PKEY_encrypt_init_ex",
        "_EVP_PKEY_free",
        "_EVP_PKEY_fromdata",
        "_EVP_PKEY_fromdata_init",
        "_EVP_PKEY_generate",
        "_EVP_PKEY_get_bn_param",
        "_EVP_PKEY_get_octet_string_param",
        "_EVP_PKEY_get_utf8_string_param",
        "_EVP_PKEY_keygen_init",
        "_EVP_PKEY_up_ref",
        "_EVP_CipherFinal",
        "_EVP_CipherInit_ex2",
        "_EVP_CipherUpdate",
        "_EVP_KDF_CTX_free",
        "_EVP_KDF_CTX_new",
        "_EVP_KDF_derive",
        "_EVP_KDF_fetch",
        "_EVP_KDF_free",
        "_EVP_PKEY_derive",
        "_EVP_PKEY_derive_init",
        "_EVP_PKEY_derive_set_peer",
        "_OSSL_DECODER_CTX_free",
        "_OSSL_DECODER_CTX_new_for_pkey",
        "_OSSL_DECODER_from_data",
        "_OSSL_EC_curve_nid2name",
        "_OSSL_ENCODER_CTX_free",
        "_OSSL_ENCODER_CTX_new_for_pkey",
        "_OSSL_ENCODER_to_data",
        "_OSSL_PARAM_construct_end",
        "_OSSL_PARAM_construct_int",
        "_OSSL_PARAM_construct_octet_string",
        "_OSSL_PARAM_construct_uint",
        "_OSSL_PARAM_construct_utf8_string",
        "_OSSL_PARAM_construct_BN",
        "_OSSL_PARAM_construct_uint32",
        "_OBJ_nid2obj",
        "_OBJ_obj2txt",
        "_OBJ_sn2nid",
        "_OpenSSL_version",
        "_d2i_ECDSA_SIG",
        "_i2d_ECDSA_SIG",

        "_OBJC_CLASS_\$_FKUserDefaultsPlugin",
        "_OBJC_CLASS_\$_FlipperClient",
        "_OBJC_CLASS_\$_FlipperKitNetworkPlugin",
        "_OBJC_CLASS_\$_SKIOSNetworkAdapter",
        "_OBJC_CLASS_\$_SKRequestInfo",
        "_OBJC_CLASS_\$_SKResponseInfo",

        "_OBJC_CLASS_\$_RTCMTLVideoView",
        "_OBJC_CLASS_\$__TtC15DyteiOSSocketIO16SocketAckEmitter",
        "_OBJC_CLASS_\$__TtC15DyteiOSSocketIO8SocketIo",

        // com.juul.datadog:bundled-iosarm64:0.1.0
        "_OBJC_CLASS_\$__TtC11DatadogObjc15DDConfiguration",
        "_OBJC_CLASS_\$__TtC11DatadogObjc17DDTrackingConsent",
        "_OBJC_CLASS_\$__TtC11DatadogObjc19DDLogsConfiguration",
        "_OBJC_CLASS_\$__TtC11DatadogObjc21DDLoggerConfiguration",
        "_OBJC_CLASS_\$__TtC11DatadogObjc6DDLogs",
        "_OBJC_CLASS_\$__TtC11DatadogObjc6DDSite",
        "_OBJC_CLASS_\$__TtC11DatadogObjc8DDLogger",
        "_OBJC_CLASS_\$__TtC11DatadogObjc9DDDatadog",
        "_OBJC_CLASS_\$__TtC11DatadogObjc16DDInternalLogger",
        "_OBJC_CLASS_\$_DDSessionReplay",
        "_OBJC_CLASS_\$_DDSessionReplayConfiguration",

        // ai.botstacks:chat-sdk-iosarm64:1.0.3
        "_OBJC_CLASS_\$_GMSMapView",
        "_OBJC_CLASS_\$_GMSMapViewOptions",
        "_OBJC_CLASS_\$__TtC10GiphyUISDK19GiphyViewController",
        "_OBJC_CLASS_\$__TtC10GiphyUISDK5Giphy",
        "_OBJC_CLASS_\$__TtC10GiphyUISDK8GPHTheme",

        // com.myunidays:launchdarkly-iosarm64:0.1.0
        "_OBJC_CLASS_\$_LDClient",
        "_OBJC_CLASS_\$_LDConfig",
        "_OBJC_CLASS_\$_LDContextBuilder",
        "_OBJC_CLASS_\$_LDMultiContextBuilder",
        "_OBJC_CLASS_\$_LDValue",
        "_OBJC_CLASS_\$_Reference",

        // com.myunidays:newrelik-iosarm64:0.0.1
        "_OBJC_CLASS_\$_NewRelic",

        // com.powersync:core-iosarm64:0.0.1-ALPHA9
        "_sqlite3_powersync_init",

        // io.github.3moly:compose-barcode-iosarm64:0.1.0
        "_OBJC_CLASS_\$_ZXImage",
        "_OBJC_CLASS_\$_ZXMultiFormatWriter",

        // io.eqoty.kryptools:aes-gcm-iosarm64
        "_compress",
        "_deflate",
        "_deflateEnd",
        "_deflateInit_",
        "_inflate",
        "_inflateEnd",
        "_inflateInit_",
        "_uncompress",
        "_zError",

        // io.github.g0dkar:qrcode-kotlin-iosarm64
        // Problem only with Xcode 14.3 because the symbol was added later
        "_UIImageHEICRepresentation",

        // DataDog
        "_OBJC_CLASS_\$_DDCrashReporter",
        "_OBJC_CLASS_\$__TtC11DatadogObjc11DDRUMAction",
        "_OBJC_CLASS_\$__TtC11DatadogObjc12DDRUMMonitor",
        "_OBJC_CLASS_\$__TtC11DatadogObjc18DDRUMConfiguration",
        "_OBJC_CLASS_\$__TtC11DatadogObjc31DDDefaultUIKitRUMViewsPredicate",
        "_OBJC_CLASS_\$__TtC11DatadogObjc33DDDefaultUIKitRUMActionsPredicate",
        "_OBJC_CLASS_\$__TtC11DatadogObjc5DDRUM",
        "_OBJC_CLASS_\$__TtC11DatadogObjc9DDRUMView",
        "_OBJC_CLASS_\$_DDWebViewTracking",

        "_OBJC_CLASS_\$__TtC11DatadogObjc26DDRUMErrorEventErrorCauses",
        "_OBJC_CLASS_\$__TtC11DatadogObjc26DDRUMViewEventDDPageStates",
        "_OBJC_CLASS_\$__TtC11DatadogObjc27DDRUMErrorEventErrorThreads",
        "_OBJC_CLASS_\$__TtC11DatadogObjc32DDRUMErrorEventErrorBinaryImages",
        "_OBJC_CLASS_\$__TtC11DatadogObjc37DDRUMViewEventViewInForegroundPeriods",

        "_OBJC_CLASS_\$__TtC20DatadogSessionReplay15DDSessionReplay",
        "_OBJC_CLASS_\$__TtC20DatadogSessionReplay28DDSessionReplayConfiguration",

        "_OBJC_CLASS_\$_DDConfiguration",
        "_OBJC_CLASS_\$_DDDatadog",
        "_OBJC_CLASS_\$_DDSite",
        "_OBJC_CLASS_\$_DDTrackingConsent",
        "_OBJC_CLASS_\$_DDLogger",
        "_OBJC_CLASS_\$_DDLoggerConfiguration",
        "_OBJC_CLASS_\$_DDLogs",
        "_OBJC_CLASS_\$_DDLogsConfiguration",

        // com.dilivva:google-places-iosarm64
        "_CLLocationCoordinate2DIsValid",
        "_CLLocationCoordinate2DMake",
        "_OBJC_CLASS_\$_CLLocationManager",
        "_kCLLocationCoordinate2DInvalid",

        // AppsFlyer
        "_OBJC_CLASS_\$_AppsFlyerLib",
        "_OBJC_CLASS_\$_SEGAppsFlyerIntegrationFactory",
        "_OBJC_CLASS_\$_SEGFirebaseIntegrationFactory",

        // RevenueCat
        "_OBJC_CLASS_\$_RCCommonFunctionality",
        "_OBJC_CLASS_\$_RCCustomerInfo",
        "_OBJC_CLASS_\$_RCPaywallFooterViewController",

        // com.usetada.wallet.core:tada-wallet-kit-iosarm64
        "_OBJC_CLASS_\$_NBPhoneNumberUtil",

        // dev.topping:toppingkotlin-iosarm64
        "_OBJC_CLASS_\$_LGColorParser",
        "_OBJC_CLASS_\$_LGColorState",
        "_OBJC_CLASS_\$_LGConstraintBarrier",
        "_OBJC_CLASS_\$_LGConstraintCarousel",
        "_OBJC_CLASS_\$_LGConstraintCircularFlow",
        "_OBJC_CLASS_\$_LGConstraintFlow",
        "_OBJC_CLASS_\$_LGConstraintGrid",
        "_OBJC_CLASS_\$_LGConstraintGroup",
        "_OBJC_CLASS_\$_LGConstraintGuideline",
        "_OBJC_CLASS_\$_LGConstraintImageFilterButton",
        "_OBJC_CLASS_\$_LGConstraintImageFilterView",
        "_OBJC_CLASS_\$_LGConstraintLayer",
        "_OBJC_CLASS_\$_LGConstraintMotionButton",
        "_OBJC_CLASS_\$_LGConstraintMotionEffect",
        "_OBJC_CLASS_\$_LGConstraintMotionLayout",
        "_OBJC_CLASS_\$_LGConstraintMotionPlaceholder",
        "_OBJC_CLASS_\$_LGConstraintPlaceholder",
        "_OBJC_CLASS_\$_LGConstraintReactiveGuide",
        "_OBJC_CLASS_\$_LGDrawableParser",
        "_OBJC_CLASS_\$_LGDrawableReturn",
        "_OBJC_CLASS_\$_LGFontParser",
        "_OBJC_CLASS_\$_LGFontReturn",
        "_OBJC_CLASS_\$_LGIdParser",
        "_OBJC_CLASS_\$_LGStringParser",
        "_OBJC_CLASS_\$_LGValueParser",
        "_OBJC_CLASS_\$__TtC7Topping16ToppingResources",

        // WeChat
        "_OBJC_CLASS_\$_PayReq",
        "_OBJC_CLASS_\$_SendAuthReq",
        "_OBJC_CLASS_\$_SendAuthResp",
        "_OBJC_CLASS_\$_SendMessageToWXReq",
        "_OBJC_CLASS_\$_WXApi",
        "_OBJC_CLASS_\$_WXImageObject",
        "_OBJC_CLASS_\$_WXLaunchMiniProgramReq",
        "_OBJC_CLASS_\$_WXLaunchMiniProgramResp",
        "_OBJC_CLASS_\$_WXMediaMessage",
        "_OBJC_CLASS_\$_WXMiniProgramObject",
        "_OBJC_CLASS_\$_WXMusicVideoObject",
        "_OBJC_CLASS_\$_WXOpenCustomerServiceReq",
        "_OBJC_CLASS_\$_WXVideoObject",
        "_OBJC_CLASS_\$_WXWebpageObject",

        // BidApp
        "_OBJC_CLASS_\$_BIDAdFormat",
        "_OBJC_CLASS_\$_BIDBannerView",
        "_OBJC_CLASS_\$_BIDConfiguration",
        "_OBJC_CLASS_\$_BIDConsent",
        "_OBJC_CLASS_\$_BIDInterstitial",
        "_OBJC_CLASS_\$_BIDRewarded",
        "_OBJC_CLASS_\$_BidappAds",

        // Dyte
        "_OBJC_CLASS_\$_DyteRTCVideoEncoderFactorySimulcast",

        // io.github.hellomr3:KmpPictureSelector-iosarm64
        "_OBJC_CLASS_\$_TZImagePickerController",

        // Lottie
        "_OBJC_CLASS_\$__TtC6Lottie23CompatibleAnimationView",

        // Yandex MapKit
        "_OBJC_CLASS_\$_YMKAnimation",
        "_OBJC_CLASS_\$_YMKBoundingBox",
        "_OBJC_CLASS_\$_YMKCameraPosition",
        "_OBJC_CLASS_\$_YMKCircle",
        "_OBJC_CLASS_\$_YMKGeometry",
        "_OBJC_CLASS_\$_YMKIconStyle",
        "_OBJC_CLASS_\$_YMKLinearRing",
        "_OBJC_CLASS_\$_YMKMapKit",
        "_OBJC_CLASS_\$_YMKMapView",
        "_OBJC_CLASS_\$_YMKMultiPolygon",
        "_OBJC_CLASS_\$_YMKPoint",
        "_OBJC_CLASS_\$_YMKPolygon",
        "_OBJC_CLASS_\$_YMKPolyline",
        "_OBJC_CLASS_\$_YMKPolylinePosition",
        "_OBJC_CLASS_\$_YMKScreenPoint",
        "_OBJC_CLASS_\$_YMKScreenRect",
        "_OBJC_CLASS_\$_YMKSubpolyline",
        "_OBJC_CLASS_\$_YMKTextStyle",
        "_OBJC_CLASS_\$_YMKVisibleRegion",
        "_OBJC_CLASS_\$_YMKBaseMapObjectCollection",
        "_OBJC_CLASS_\$_YMKCircleMapObject",
        "_OBJC_CLASS_\$_YMKClusterizedPlacemarkCollection",
        "_OBJC_CLASS_\$_YMKLogoAlignment",
        "_OBJC_CLASS_\$_YMKLogoPadding",
        "_OBJC_CLASS_\$_YMKMapObjectCollection",
        "_OBJC_CLASS_\$_YMKPlacemarkMapObject",
        "_OBJC_CLASS_\$_YMKPolygonMapObject",
        "_OBJC_CLASS_\$_YMKPolylineMapObject",
        "_OBJC_CLASS_\$_YMKUserLocationAnchorChanged",
        "_OBJC_CLASS_\$_YMKUserLocationIconChanged",
        "_OBJC_CLASS_\$_YMKLocation",
        "_OBJC_CLASS_\$_YMKLocationViewSourceFactory",
        "_OBJC_CLASS_\$_YMKRect",
        "_OBJC_CLASS_\$_YMKLineStyle",
        "_OBJC_CLASS_\$_YMKLocationSubscriptionSettings",
        "_OBJC_CLASS_\$_YMKGeo",
        "_OBJC_CLASS_\$_YMKSegment",

        // GuimauveApp
        "_OBJC_CLASS_\$_SwiftUIGuimauveApp",

        // Google Ads
        "_GADAdSizeBanner",
        "_GADAdSizeFluid",
        "_GADAdSizeFullBanner",
        "_GADAdSizeInvalid",
        "_GADAdSizeLargeBanner",
        "_GADAdSizeLeaderboard",
        "_GADAdSizeMediumRectangle",
        "_GADAdSizeSkyscraper",
        "_GADErrorDomain",
        "_GADCurrentOrientationAnchoredAdaptiveBannerAdSizeWithWidth",
        "_OBJC_CLASS_\$_GADBannerView",
        "_OBJC_CLASS_\$_GADInterstitialAd",
        "_OBJC_CLASS_\$_GADMobileAds",
        "_OBJC_CLASS_\$_GADRequest",
        "_OBJC_CLASS_\$_GADRewardedAd",
        "_OBJC_CLASS_\$_GADRewardedInterstitialAd",
        "_OBJC_CLASS_\$__TtC6KAdmob13KBannerAdView",
        "_OBJC_CLASS_\$__TtC6KAdmob20RewardedAdController",
        "_OBJC_CLASS_\$__TtC6KAdmob24InterstitialAdController",
        "_OBJC_CLASS_\$__TtC6KAdmob32RewardedInterstitialAdController",

        // io.github.sbenmeddour:mdk-compose-iosarm64
        "_MDK_getGlobalOptionInt32",
        "_MDK_getGlobalOptionString",
        "_MDK_setGlobalOptionFloat",
        "_MDK_setGlobalOptionInt32",
        "_MDK_setGlobalOptionString",

        // io.github.smyrgeorge:sqlx4k-iosarm64
        "_sqlx4k_free_result",

        // io.github.the-best-is-best:compose-check-for-update-iosarm64
        "_OBJC_CLASS_\$__TtC8KUpdater8KUpdater",

        // Facebook
        "_FBLinkable_NSBundle_InfoDictionaryProviding",
        "_FBLinkable_NSData_FileDataExtracting",
        "_FBLinkable_NSFileManager_FileManaging",
        "_FBLinkable_NSNotificationCenter_NotificationDelivering",
        "_FBLinkable_NSNotificationCenter_NotificationPosting",
        "_FBLinkable_NSProcessInfo_MacCatalystDetermining",
        "_FBLinkable_NSProcessInfo_OperatingSystemVersionComparing",
        "_FBLinkable_NSURLSessionTask_NetworkTask",
        "_FBLinkable_NSURLSession_URLSessionProviding",
        "_FBLinkable_NSUserDefaults_DataPersisting",
        "_FBLinkable_UIPasteboard_FBSDKPasteboard",
        "_OBJC_CLASS_\$_FBSDKAccessToken",
        "_OBJC_CLASS_\$_FBSDKGraphRequest",
        "_OBJC_CLASS_\$_FBSDKLoginManager",

        // io.github.the-best-is-best:kapp-auth-iosarm64
        "_OBJC_CLASS_\$__TtC9KServices9KServices",

        // Google Maps
        "_OBJC_CLASS_\$__TtC10KGoogleMap10MarkerData",
        "_OBJC_CLASS_\$__TtC10KGoogleMap14KGoogleMapInit",
        "_OBJC_CLASS_\$__TtC10KGoogleMap8KMapView",

        // io.github.thearchitect123:titansocket-iosarm64
        "_deflateInit2_",
        "_inflateInit2_",
        "_zlibVersion",

        // Scanbot
        "_OBJC_CLASS_\$_SBSDKUI2BarcodeItem",
        "_OBJC_CLASS_\$_SBSDKUI2BarcodeScannerConfiguration",
        "_OBJC_CLASS_\$__TtC10ScanbotSDK36SBSDKUI2BarcodeScannerViewController",
        "_OBJC_CLASS_\$__TtC10ScanbotSDK7Scanbot",

        // MapLibre
        "_MLNAltitudeForZoomLevel",
        "_MLNShapeSourceOptionBuffer",
        "_MLNShapeSourceOptionClusterProperties",
        "_MLNShapeSourceOptionClusterRadius",
        "_MLNShapeSourceOptionClustered",
        "_MLNShapeSourceOptionLineDistanceMetrics",
        "_MLNShapeSourceOptionMaximumZoomLevel",
        "_MLNShapeSourceOptionMaximumZoomLevelForClustering",
        "_MLNShapeSourceOptionMinimumZoomLevel",
        "_MLNShapeSourceOptionSimplificationTolerance",
        "_MLNZoomLevelForAltitude",
        "_OBJC_CLASS_\$_MLNAttributionInfo",
        "_OBJC_CLASS_\$_MLNBackgroundStyleLayer",
        "_OBJC_CLASS_\$_MLNCircleStyleLayer",
        "_OBJC_CLASS_\$_MLNFillExtrusionStyleLayer",
        "_OBJC_CLASS_\$_MLNFillStyleLayer",
        "_OBJC_CLASS_\$_MLNHeatmapStyleLayer",
        "_OBJC_CLASS_\$_MLNHillshadeStyleLayer",
        "_OBJC_CLASS_\$_MLNLineStyleLayer",
        "_OBJC_CLASS_\$_MLNLoggingConfiguration",
        "_OBJC_CLASS_\$_MLNMapCamera",
        "_OBJC_CLASS_\$_MLNMapView",
        "_OBJC_CLASS_\$_MLNRasterStyleLayer",
        "_OBJC_CLASS_\$_MLNRasterTileSource",
        "_OBJC_CLASS_\$_MLNShape",
        "_OBJC_CLASS_\$_MLNShapeSource",
        "_OBJC_CLASS_\$_MLNSource",
        "_OBJC_CLASS_\$_MLNStyleLayer",
        "_OBJC_CLASS_\$_MLNSymbolStyleLayer",
        "_OBJC_CLASS_\$_MLNTileSource",
        "_OBJC_CLASS_\$_MLNVectorTileSource",
        "_MLNTileSourceOptionAttributionHTMLString",
        "_MLNTileSourceOptionCoordinateBounds",
        "_MLNTileSourceOptionMaximumZoomLevel",
        "_MLNTileSourceOptionMinimumZoomLevel",
        "_MLNTileSourceOptionTileCoordinateSystem",
        "_MLNTileSourceOptionTileSize",

        // PubNub
        "_OBJC_CLASS_\$__TtC9PubNubSDK10KMPAnyJSON",
        "_OBJC_CLASS_\$__TtC9PubNubSDK13KMPHashedPage",
        "_OBJC_CLASS_\$__TtC9PubNubSDK14KMPBoundedPage",
        "_OBJC_CLASS_\$__TtC9PubNubSDK15KMPSubscription",
        "_OBJC_CLASS_\$__TtC9PubNubSDK15KMPUserMetadata",
        "_OBJC_CLASS_\$__TtC9PubNubSDK16KMPEventListener",
        "_OBJC_CLASS_\$__TtC9PubNubSDK16KMPMessageAction",
        "_OBJC_CLASS_\$__TtC9PubNubSDK17KMPPresenceChange",
        "_OBJC_CLASS_\$__TtC9PubNubSDK17KMPStatusListener",
        "_OBJC_CLASS_\$__TtC9PubNubSDK18KMPChannelMetadata",
        "_OBJC_CLASS_\$__TtC9PubNubSDK18KMPSubscriptionSet",
        "_OBJC_CLASS_\$__TtC9PubNubSDK20KMPDataUploadContent",
        "_OBJC_CLASS_\$__TtC9PubNubSDK20KMPFileUploadContent",
        "_OBJC_CLASS_\$__TtC9PubNubSDK20KMPUserIncludeFields",
        "_OBJC_CLASS_\$__TtC9PubNubSDK21KMPMembershipMetadata",
        "_OBJC_CLASS_\$__TtC9PubNubSDK21KMPObjectSortProperty",
        "_OBJC_CLASS_\$__TtC9PubNubSDK22KMPHereNowOccupantData",
        "_OBJC_CLASS_\$__TtC9PubNubSDK22KMPMemberIncludeFields",
        "_OBJC_CLASS_\$__TtC9PubNubSDK22KMPSetMembershipResult",
        "_OBJC_CLASS_\$__TtC9PubNubSDK23KMPChannelIncludeFields",
        "_OBJC_CLASS_\$__TtC9PubNubSDK24KMPSetUUIDMetadataResult",
        "_OBJC_CLASS_\$__TtC9PubNubSDK25KMPRemoveMembershipResult",
        "_OBJC_CLASS_\$__TtC9PubNubSDK26KMPMembershipIncludeFields",
        "_OBJC_CLASS_\$__TtC9PubNubSDK27KMPInputStreamUploadContent",
        "_OBJC_CLASS_\$__TtC9PubNubSDK27KMPRemoveUUIDMetadataResult",
        "_OBJC_CLASS_\$__TtC9PubNubSDK27KMPSetChannelMetadataResult",
        "_OBJC_CLASS_\$__TtC9PubNubSDK30KMPRemoveChannelMetadataResult",
        "_OBJC_CLASS_\$__TtC9PubNubSDK7KMPFile",
        "_OBJC_CLASS_\$__TtC9PubNubSDK8KMPError",
        "_OBJC_CLASS_\$__TtC9PubNubSDK9KMPPubNub",

        // mpv
        "_mpv_command",
        "_mpv_command_string",
        "_mpv_create",
        "_mpv_destroy",
        "_mpv_get_property",
        "_mpv_initialize",
        "_mpv_observe_property",
        "_mpv_render_context_create",
        "_mpv_render_context_free",
        "_mpv_render_context_render",
        "_mpv_render_context_set_update_callback",
        "_mpv_request_log_messages",
        "_mpv_set_option",
        "_mpv_set_option_string",
        "_mpv_set_property",
        "_mpv_set_property_string",
        "_mpv_wait_event",
        "_OBJC_CLASS_\$_VLCMedia",
        "_OBJC_CLASS_\$_VLCMediaPlayer",
        "_OBJC_CLASS_\$_VLCMediaPlayerTrack",
        "_OBJC_CLASS_\$_VLCTime",

        "_OBJC_CLASS_\$__TtC13YouTubePlayer17YouTubePlayerView",

        // Yandex ads
        "_OBJC_CLASS_\$_YMAAdRequestConfiguration",
        "_OBJC_CLASS_\$_YMAAdView",
        "_OBJC_CLASS_\$_YMAAppOpenAdLoader",
        "_OBJC_CLASS_\$_YMABannerAdSize",
        "_OBJC_CLASS_\$_YMAMobileAds",

        // GoogleMapsUtils
        "_OBJC_CLASS_\$_GMUClusterManager",
        "_OBJC_CLASS_\$_GMUDefaultClusterIconGenerator",
        "_OBJC_CLASS_\$_GMUDefaultClusterRenderer",
        "_OBJC_CLASS_\$_GMUHeatmapTileLayer",
        "_OBJC_CLASS_\$_GMUNonHierarchicalDistanceBasedAlgorithm",
        "_OBJC_CLASS_\$_GMUWeightedLatLng",

        // MLKitVision
        "_OBJC_CLASS_\$_MLKBarcode",
        "_OBJC_CLASS_\$_MLKBarcodeScanner",
        "_OBJC_CLASS_\$_MLKVisionImage",

        // Firebase Auth UI
        "_OBJC_CLASS_\$_FUIAuth",
        "_OBJC_CLASS_\$_FUIEmailAuth",
        "_OBJC_CLASS_\$_FUIFacebookAuth",
        "_OBJC_CLASS_\$_FUIGoogleAuth",
        "_OBJC_CLASS_\$_FUIPasswordSignInViewController",
        "_FIRFacebookAuthProviderID",
        "_FIRGitHubAuthProviderID",
        "_FIRGoogleAuthProviderID",
        "_FIRTwitterAuthProviderID",

        // UserMessagingPlatform
        "_OBJC_CLASS_\$_UMPConsentForm",
        "_OBJC_CLASS_\$_UMPConsentInformation",
        "_OBJC_CLASS_\$_UMPDebugSettings",
        "_OBJC_CLASS_\$_UMPRequestParameters",

        // OpenKuiklyIOSRender
        "_OBJC_CLASS_\$_KuiklyRenderThreadManager",

        // TFLTensorFlowLite
        "_OBJC_CLASS_\$_TFLMetalDelegate",
        "_OBJC_CLASS_\$_TFLMetalDelegateOptions",

        // MediaPipeTasksVision
        "_OBJC_CLASS_\$_MPPBaseOptions",
        "_OBJC_CLASS_\$_MPPCategory",
        "_OBJC_CLASS_\$_MPPDetection",
        "_OBJC_CLASS_\$_MPPImage",
        "_OBJC_CLASS_\$_MPPNormalizedLandmark",
        "_OBJC_CLASS_\$_MPPObjectDetector",
        "_OBJC_CLASS_\$_MPPObjectDetectorOptions",
        "_OBJC_CLASS_\$_MPPPoseLandmarker",
        "_OBJC_CLASS_\$_MPPPoseLandmarkerOptions",

        // FirebaseAIBridge
        "_OBJC_CLASS_\$_FileDataPartObjc",
        "_OBJC_CLASS_\$_FirebaseObjc",
        "_OBJC_CLASS_\$_ImagePartObjc",
        "_OBJC_CLASS_\$_InlineDataPartObjc",
        "_OBJC_CLASS_\$_PartObjc",
        "_OBJC_CLASS_\$_TextPartObjc",
        "_OBJC_CLASS_\$__TtC16FirebaseAIBridge12CitationObjc",
        "_OBJC_CLASS_\$__TtC16FirebaseAIBridge13CandidateObjc",
        "_OBJC_CLASS_\$__TtC16FirebaseAIBridge16ModelContentObjc",
        "_OBJC_CLASS_\$__TtC16FirebaseAIBridge16SafetyRatingObjc",
        "_OBJC_CLASS_\$__TtC16FirebaseAIBridge22ModalityTokenCountObjc",
        "_OBJC_CLASS_\$__TtC16FirebaseAIBridge27GenerateContentResponseObjc",

        // AppAuth
        "_OBJC_CLASS_\$__TtC9kmmcrypto16IOSCryptoManager",

        // InspireFace
        "_HFCreateImageStream",
        "_HFCreateInspireFaceSessionOptional",
        "_HFExecuteFaceTrack",
        "_HFFaceComparison",
        "_HFFaceFeatureExtract",
        "_HFGetFaceInteractionActionsResult",
        "_HFGetFaceQualityConfidence",
        "_HFGetFeatureLength",
        "_HFLaunchInspireFace",
        "_HFMultipleFacePipelineProcessOptional",
        "_HFReleaseImageStream",
        "_HFReleaseInspireFaceSession",
        "_HFSessionSetFaceDetectThreshold",
        "_HFSessionSetFilterMinimumFacePixelSize",
        "_HFSessionSetTrackPreviewSize",
        "_HFTerminateInspireFace",

        // PusherSwift
        "_OBJC_CLASS_\$__TtC11PusherSwift12OCAuthMethod",
        "_OBJC_CLASS_\$__TtC11PusherSwift12OCPusherHost",
        "_OBJC_CLASS_\$__TtC11PusherSwift19PusherClientOptions",
        "_OBJC_CLASS_\$__TtC11PusherSwift6Pusher",

        // swiftXPC
        "__swift_FORCE_LOAD_\$_swiftXPC",

        // SwiftUICore
        "_OBJC_CLASS_\$_ArchDetect",
        "_OBJC_CLASS_\$_FFmpegKit",
        "_OBJC_CLASS_\$_FFmpegKitConfig",
        "_OBJC_CLASS_\$_FFmpegSession",
        "_OBJC_CLASS_\$_FFprobeSession",
        "_OBJC_CLASS_\$_Log",
        "_OBJC_CLASS_\$_Statistics",

        // androidx.sqlite:sqlite-framework-iosarm64
        // Likely provided by a different version of sqlite3
        "_sqlite3_load_extension",

        // com.viktormykhailiv:health-kmp-iosarm64
        "_OBJC_CLASS_\$_CLLocation"
    )
}
