package co.touchlab.skie.plugin.libraries.dependencies.swift

import co.touchlab.skie.plugin.libraries.library.Component

object SwiftLibraryDependencyProvider {

    private val mapping = mapOf(
        SystemLibrary.sqlite3 to setOf(
            "app.cash.redwood:redwood-treehouse-host-iosarm64",
            "app.cash.sqldelight:native-driver-iosarm64",
            "app.cash.zipline:zipline-loader-iosarm64",
            "co.touchlab:sqliter-driver-iosarm64",
            "co.touchlab:sqliter-iosarm64",
            "com.apollographql.apollo3:apollo-normalized-cache-sqlite-incubating-iosarm64",
            "com.apollographql.apollo3:apollo-normalized-cache-sqlite-iosarm64",
            "com.ctrip.kotlin:sqllin-driver-iosarm64",
            "com.ctrip.kotlin:sqllin-dsl-iosarm64",
            "com.ditchoom:mqtt-4-models-iosarm64",
            "com.ditchoom:mqtt-5-models-iosarm64",
            "com.ditchoom:mqtt-client-iosarm64",
            "com.intsoftdev:nrservices-iosarm64",
            "com.intsoftdev:nrstations-iosarm64",
            "com.intsoftdev:sdknrservices-iosarm64",
            "com.intsoftdev:sdknrstations-iosarm64",
            "com.mobilejazz:harmony-kotlin-iosarm64",
            "com.squareup.sqldelight:native-driver-iosarm64",
            "com.unflow:shared-iosarm64",
            "io.branch.sdk.nativecompute:native-compute-sdk-iosarm64",
            "io.github.chopyourbrain:kontrol-iosarm64",
            "io.github.pablichjenkov:amadeus-api-iosarm64",
            "io.github.softartdev:sqlcipher-ktn-pod-iosarm64",
            "net.mbonnin.sqldelight:native-driver-iosarm64",
            "org.danbrough.sqldelight:native-driver-iosarm64",
            "org.danbrough.touchlab:sqliter-driver-iosarm64",
            "org.danbrough:sqliter-driver-iosarm64",
            "io.github.rotbolt:flaker-data-iosarm64",
            "io.github.react-native-async-storage:async-storage-sqlite-iosarm64",
            "com.outsidesource:oskit-kmp-iosarm64",
            "com.m2f-kt:archer-core-iosarm64",
            "com.m2f-kt:archer-iosarm64",
            "com.m2f-kt:database-iosarm64",
            "androidx.sqlite:sqlite-framework-iosarm64",
            "cloud.proxi:shared-iosArm64",
            "com.apollographql.apollo:apollo-normalized-cache-sqlite-iosarm64",
            "com.apollographql.cache:normalized-cache-sqlite-incubating-iosarm64",
            "com.bidyut.tech.seahorse:core-iosarm64",
            "com.bidyut.tech.seahorse:seahorse-sqlite-iosarm64",
            "com.latenighthack.ktstore:ktstore-library-iosarm64",
            "io.github.irgaly.kottage:kottage-data-sqlite-iosArm64",
            "io.github.irgaly.kottage:kottage-iosArm64",
            "io.github.shabinder:zipline-loader-iosarm64",
            "io.github.vicaloy:shared-iosarm64",
            "io.monaru:shared-iosarm64",
            "io.exoquery:terpal-sql-native-iosarm64",
            "io.github.bvantur:inspektify-iosarm64",
            "io.github.bvantur:inspektify-ktor2-iosarm64",
            "io.github.bvantur:inspektify-ktor3-iosarm64",
            "io.github.bvantur:inspektifyLib-iosarm64",
            "io.telereso.kmp.sqldelight:native-driver-iosarm64",
            "io.telereso.kmp:core-iosarm64",
            "io.telereso.kmp:core-test-iosarm64",
            "org.apptank.horus:client-iosarm64",
            "ch.ubique.kmp:network-iosarm64",
            "com.addhen.kanalytics:kanalytics-viewer-iosarm64",
            "com.gyanoba.inspektor:inspektor-iosarm64",
            "dev.mattramotar.meeseeks:runtime-iosarm64",
            "me.gulya.sqldelight:native-driver-iosarm64",
            "ro.cosminmihu.ktor:ktor-monitor-logging-iosarm64",
            "com.aarkaystudio.biblekit:biblekit-db-iosarm64",
            "com.aarkaystudio.biblekit:biblekit-iosarm64",
            "com.apollographql.cache:normalized-cache-sqlite-iosarm64",
            "global.deveng:networking-kmp-iosarm64",
            "io.exoquery:controller-native-iosarm64",
            "io.exoquery:exoquery-native-iosarm64",
            "io.exoquery:exoquery-runner-native-iosarm64",
            "io.github.keremturker:logging-iosarm64",
        ),
    )

    fun getSystemLibraries(component: Component): List<SystemLibrary> =
        mapping.filterValues { component.module.fqName in it }.keys.toList()
}
