package co.touchlab.skie.plugin.libraries.dependencies.swift

import co.touchlab.skie.plugin.libraries.library.Component

object SwiftFrameworkDependencyProvider {

    private val mapping = mapOf(
        SystemFramework.CoreText to setOf(
            "app.cash.redwood:redwood-lazylayout-composeui-iosarm64",
            "app.cash.redwood:redwood-treehouse-composeui-insets-iosarm64",
            "app.cash.redwood:redwood-treehouse-composeui-iosarm64",
            "app.cash.redwood:redwood-treehouse-lazylayout-composeui-iosarm64",
            "com.arkivanov.decompose:extensions-compose-jetbrains-iosarm64",
            "com.carelesscoyotes.remotedata:remotedata-compose-iosarm64",
            "com.dragselectcompose:core-iosarm64",
            "com.dragselectcompose:dragselect-iosarm64",
            "com.dragselectcompose:extensions-iosarm64",
            "com.dragselectcompose:grid-iosarm64",
            "com.github.anastr:speedometer-iosarm64",
            "com.hexascribe:chatbot-builder-iosarm64",
            "com.materialkolor:material-kolor-iosarm64",
            "com.mikepenz:aboutlibraries-compose-iosarm64",
            "com.mohamedrejeb.richeditor:richeditor-compose-iosarm64",
            "com.mxalbert.zoomable:zoomable-iosarm64",
            "com.slack.circuit:circuit-backstack-iosarm64",
            "com.slack.circuit:circuit-foundation-iosarm64",
            "com.slack.circuit:circuit-overlay-iosarm64",
            "com.slack.circuit:circuit-runtime-ui-iosarm64",
            "dev.chrisbanes.circuit:circuit-backstack-iosarm64",
            "dev.chrisbanes.circuit:circuit-foundation-iosarm64",
            "dev.chrisbanes.circuit:circuit-overlay-iosarm64",
            "dev.chrisbanes.circuit:circuit-runtime-ui-iosarm64",
            "dev.chrisbanes.material3:material3-window-size-class-multiplatform-iosarm64",
            "dev.icerock.moko:media-compose-iosarm64",
            "io.github.alexgladkov:odyssey-android-iosarm64",
            "io.github.alexgladkov:odyssey-core-iosarm64",
            "io.github.dmitriy1892.kmm:kmm-mvvm-compose-iosarm64",
            "io.github.dmitriy1892.kmm:mvvm-compose-iosarm64",
            "io.github.epicarchitect:calendar-compose-basis-iosarm64",
            "io.github.epicarchitect:calendar-compose-datepicker-iosarm64",
            "io.github.epicarchitect:calendar-compose-pager-iosarm64",
            "io.github.epicarchitect:calendar-compose-ranges-iosarm64",
            "io.github.fornewid:material-motion-compose-core-iosarm64",
            "io.github.luca992.com.alialbaali.kamel:kamel-core-iosarm64",
            "io.github.luca992.com.alialbaali.kamel:kamel-image-iosarm64",
            "io.github.overpas:treemap-chart-compose-iosarm64",
            "io.github.pablichjenkov:component-iosarm64",
            "io.github.pablichjenkov:component-toolkit-iosarm64",
            "io.github.pablichjenkov:templato-components-iosarm64",
            "io.github.qdsfdhvh:image-loader-extension-blur-iosarm64",
            "io.github.qdsfdhvh:image-loader-extension-moko-resources-iosarm64",
            "io.github.xxfast:decompose-router-iosarm64",
            "media.kamel:kamel-core-iosarm64",
            "media.kamel:kamel-image-iosarm64",
            "org.jetbrains.skiko:skiko-iosarm64",
            "xyz.ramotar.catjam:catjam-iosarm64",
            "pl.speednet.c-shadow:cshadow-iosarm64",
            "io.github.thechance101:chart-iosarm64",
            "eu.codlab:kotlin-moko-resources-ext-iosarm64",
            "eu.codlab:kotlin-moko-maps-compose-iosarm64",
            "eu.codlab:tcg-data-pricing-iosarm64",
            "eu.codlab:tcg-mapper-iosarm64",
        ),
        SystemFramework.CoreGraphics to setOf(
            "app.cash.redwood:redwood-lazylayout-composeui-iosarm64",
            "app.cash.redwood:redwood-treehouse-composeui-insets-iosarm64",
            "app.cash.redwood:redwood-treehouse-composeui-iosarm64",
            "app.cash.redwood:redwood-treehouse-lazylayout-composeui-iosarm64",
            "com.arkivanov.decompose:extensions-compose-jetbrains-iosarm64",
            "com.carelesscoyotes.remotedata:remotedata-compose-iosarm64",
            "com.dragselectcompose:core-iosarm64",
            "com.dragselectcompose:dragselect-iosarm64",
            "com.dragselectcompose:extensions-iosarm64",
            "com.dragselectcompose:grid-iosarm64",
            "com.materialkolor:material-kolor-iosarm64",
            "com.mikepenz:aboutlibraries-compose-iosarm64",
            "com.mohamedrejeb.richeditor:richeditor-compose-iosarm64",
            "com.mxalbert.zoomable:zoomable-iosarm64",
            "com.slack.circuit:circuit-backstack-iosarm64",
            "com.slack.circuit:circuit-foundation-iosarm64",
            "com.slack.circuit:circuit-overlay-iosarm64",
            "com.slack.circuit:circuit-runtime-ui-iosarm64",
            "dev.chrisbanes.circuit:circuit-backstack-iosarm64",
            "dev.chrisbanes.circuit:circuit-foundation-iosarm64",
            "dev.chrisbanes.circuit:circuit-overlay-iosarm64",
            "dev.chrisbanes.circuit:circuit-runtime-ui-iosarm64",
            "dev.chrisbanes.material3:material3-window-size-class-multiplatform-iosarm64",
            "io.github.alexgladkov:odyssey-android-iosarm64",
            "io.github.alexgladkov:odyssey-core-iosarm64",
            "io.github.dmitriy1892.kmm:kmm-mvvm-compose-iosarm64",
            "io.github.dmitriy1892.kmm:mvvm-compose-iosarm64",
            "io.github.epicarchitect:calendar-compose-basis-iosarm64",
            "io.github.epicarchitect:calendar-compose-datepicker-iosarm64",
            "io.github.epicarchitect:calendar-compose-pager-iosarm64",
            "io.github.epicarchitect:calendar-compose-ranges-iosarm64",
            "io.github.fornewid:material-motion-compose-core-iosarm64",
            "io.github.luca992.com.alialbaali.kamel:kamel-core-iosarm64",
            "io.github.luca992.com.alialbaali.kamel:kamel-image-iosarm64",
            "io.github.overpas:treemap-chart-compose-iosarm64",
            "io.github.pablichjenkov:component-iosarm64",
            "io.github.pablichjenkov:component-toolkit-iosarm64",
            "io.github.pablichjenkov:templato-components-iosarm64",
            "io.github.qdsfdhvh:image-loader-extension-blur-iosarm64",
            "io.github.qdsfdhvh:image-loader-extension-moko-resources-iosarm64",
            "io.github.xxfast:decompose-router-iosarm64",
            "media.kamel:kamel-core-iosarm64",
            "media.kamel:kamel-image-iosarm64",
            "org.jetbrains.skiko:skiko-iosarm64",
            "eu.codlab:kotlin-moko-resources-ext-iosarm64",
            "io.github.thechance101:chart-iosarm64",
            "pl.speednet.c-shadow:cshadow-iosarm64",
            "xyz.ramotar.catjam:catjam-iosarm64",
            "eu.codlab:kotlin-moko-maps-compose-iosarm64",
            "eu.codlab:tcg-data-pricing-iosarm64",
            "eu.codlab:tcg-mapper-iosarm64",
        ),
        SystemFramework.AVFoundation to setOf(
            "com.soywiz.korlibs.korau:korau-iosarm64",
            "com.soywiz.korge:korge-iosarm64",
            "com.soywiz.korlibs.korge2:korge-iosarm64",
            "com.soywiz.korlibs.korge2:korge-box2d-iosarm64",
            "com.soywiz.korlibs.korge2:korge-dragonbones-iosarm64",
            "com.soywiz.korlibs.korge2:korge-spine-iosarm64",
            "com.soywiz.korlibs.korvi:korvi-iosarm64",
            "io.github.tantantan277:shared-iosarm64",
            "io.shipsy.mobilesdk:core-iosarm64",
            "io.github.rvenky125:kmp-device-info-iosarm64",
            "com.soywiz:korlibs-audio-iosarm64",
        ),
        SystemFramework.UIKit to setOf(
            "io.github.mirzemehdi:kmprevenuecat-purchases-iosarm64",
            "io.github.g0dkar:qrcode-kotlin-iosarm64:4.1.1",
        ),
    )

    fun getSystemFrameworks(component: Component): List<SystemFramework> =
        mapping.filterValues { component.module.fqName in it }.keys.toList()
}
