package co.touchlab.skie.plugin.libraries

val expectedMissingSymbols = listOf(
    "_OBJC_CLASS_\$_Bugsnag",
    "_OBJC_CLASS_\$_BugsnagError",
    "_OBJC_CLASS_\$_BugsnagFeatureFlag",
    "_OBJC_CLASS_\$_BugsnagStackframe",

    "_OBJC_CLASS_\$_FIRActionCodeInfo",
    "_OBJC_CLASS_\$_FIRActionCodeSettings",
    "_OBJC_CLASS_\$_FIRAnalytics",
    "_OBJC_CLASS_\$_FIRApp",
    "_OBJC_CLASS_\$_FIRAuth",
    "_OBJC_CLASS_\$_FIRAuthCredential",
    "_OBJC_CLASS_\$_FIRAuthDataResult",
    "_OBJC_CLASS_\$_FIRAuthSettings",
    "_OBJC_CLASS_\$_FIRAuthTokenResult",
    "_OBJC_CLASS_\$_FIRCrashlytics",
    "_OBJC_CLASS_\$_FIRDocumentChange",
    "_OBJC_CLASS_\$_FIRDocumentSnapshot",
    "_OBJC_CLASS_\$_FIREmailAuthProvider",
    "_OBJC_CLASS_\$_FIRExceptionModel",
    "_OBJC_CLASS_\$_FIRFacebookAuthProvider",
    "_OBJC_CLASS_\$_FIRFieldPath",
    "_OBJC_CLASS_\$_FIRFieldValue",
    "_OBJC_CLASS_\$_FIRFirestore",
    "_OBJC_CLASS_\$_FIRFirestoreSettings",
    "_OBJC_CLASS_\$_FIRFunctions",
    "_OBJC_CLASS_\$_FIRGitHubAuthProvider",
    "_OBJC_CLASS_\$_FIRGoogleAuthProvider",
    "_OBJC_CLASS_\$_FIRHTTPSCallableResult",
    "_OBJC_CLASS_\$_FIRInstallations",
    "_OBJC_CLASS_\$_FIRInstallationsAuthTokenResult",
    "_OBJC_CLASS_\$_FIRMessaging",
    "_OBJC_CLASS_\$_FIRMultiFactorInfo",
    "_OBJC_CLASS_\$_FIRMultiFactorSession",
    "_OBJC_CLASS_\$_FIROAuthProvider",
    "_OBJC_CLASS_\$_FIROptions",
    "_OBJC_CLASS_\$_FIRPhoneAuthProvider",
    "_OBJC_CLASS_\$_FIRRemoteConfig",
    "_OBJC_CLASS_\$_FIRRemoteConfigSettings",
    "_OBJC_CLASS_\$_FIRStackFrame",
    "_OBJC_CLASS_\$_FIRStorage",
    "_OBJC_CLASS_\$_FIRStorageMetadata",
    "_OBJC_CLASS_\$_FIRStorageReference",
    "_OBJC_CLASS_\$_FIRQuerySnapshot",
    "_OBJC_CLASS_\$_FIRTimestamp",
    "_OBJC_CLASS_\$_FIRTwitterAuthProvider",
    "_OBJC_CLASS_\$_FIRUser",
    "_FIRAuthErrorDomain",
    "_FIRCLSExceptionRecordNSException",
    "_FIRFirestoreErrorDomain",
    "_FIRRemoteConfigErrorDomain",

    "_OBJC_CLASS_\$_GIDConfiguration",
    "_OBJC_CLASS_\$_GIDSignIn",

    "_OBJC_CLASS_\$_GMSCameraPosition",
    "_OBJC_CLASS_\$_GMSCoordinateBounds",
    "_OBJC_CLASS_\$_GMSGeocoder",
    "_OBJC_CLASS_\$_GMSMarker",
    "_OBJC_CLASS_\$_GMSMutablePath",
    "_OBJC_CLASS_\$_GMSPath",
    "_OBJC_CLASS_\$_GMSPolygon",
    "_OBJC_CLASS_\$_GMSPolyline",
    "_kGMSMaxZoomLevel",
    "_kGMSMinZoomLevel",

    "_OBJC_CLASS_\$_MGLAnnotationImage",
    "_OBJC_CLASS_\$_MGLLineStyleLayer",
    "_OBJC_CLASS_\$_MGLPointAnnotation",
    "_OBJC_CLASS_\$_MGLPolygonFeature",
    "_OBJC_CLASS_\$_MGLShapeSource",

    "_OBJC_CLASS_\$_MMKV",

    "_OBJC_CLASS_\$__TtC12mokoSocketIo8SocketIo",
    "_OBJC_CLASS_\$__TtC22mokoWidgetsBottomSheet21BottomSheetController",
    "_OBJC_CLASS_\$__TtC21mokoWidgetsCollection22ALCollectionFlowLayout",
    "_OBJC_CLASS_\$__TtC25mokoWidgetsDateTimePicker25DateBottomSheetController",
    "_OBJC_CLASS_\$__TtC23mokoWidgetsImageNetwork12ImageNetwork",

    "_OBJC_CLASS_\$_MPEvent",
    "_OBJC_CLASS_\$_MParticle",

    "_olm_account",
    "_olm_account_fallback_key",
    "_olm_account_fallback_key_length",
    "_olm_account_generate_fallback_key",
    "_olm_account_generate_fallback_key_random_length",
    "_olm_account_generate_one_time_keys",
    "_olm_account_generate_one_time_keys_random_length",
    "_olm_account_identity_keys",
    "_olm_account_identity_keys_length",
    "_olm_account_last_error",
    "_olm_account_mark_keys_as_published",
    "_olm_account_max_number_of_one_time_keys",
    "_olm_account_one_time_keys",
    "_olm_account_one_time_keys_length",
    "_olm_account_sign",
    "_olm_account_signature_length",
    "_olm_account_size",
    "_olm_clear_account",
    "_olm_clear_inbound_group_session",
    "_olm_clear_outbound_group_session",
    "_olm_clear_pk_decryption",
    "_olm_clear_pk_encryption",
    "_olm_clear_pk_signing",
    "_olm_clear_sas",
    "_olm_clear_session",
    "_olm_clear_utility",
    "_olm_create_account",
    "_olm_create_account_random_length",
    "_olm_create_inbound_session",
    "_olm_create_inbound_session_from",
    "_olm_create_outbound_session",
    "_olm_create_outbound_session_random_length",
    "_olm_create_sas",
    "_olm_create_sas_random_length",
    "_olm_decrypt",
    "_olm_decrypt_max_plaintext_length",
    "_olm_ed25519_verify",
    "_olm_encrypt",
    "_olm_encrypt_message_length",
    "_olm_encrypt_message_type",
    "_olm_encrypt_random_length",
    "_olm_error",
    "_olm_export_inbound_group_session",
    "_olm_export_inbound_group_session_length",
    "_olm_group_decrypt",
    "_olm_group_decrypt_max_plaintext_length",
    "_olm_group_encrypt",
    "_olm_group_encrypt_message_length",
    "_olm_import_inbound_group_session",
    "_olm_inbound_group_session",
    "_olm_inbound_group_session_first_known_index",
    "_olm_inbound_group_session_id",
    "_olm_inbound_group_session_id_length",
    "_olm_inbound_group_session_is_verified",
    "_olm_inbound_group_session_last_error",
    "_olm_inbound_group_session_size",
    "_olm_init_inbound_group_session",
    "_olm_init_outbound_group_session",
    "_olm_init_outbound_group_session_random_length",
    "_olm_matches_inbound_session",
    "_olm_matches_inbound_session_from",
    "_olm_outbound_group_session",
    "_olm_outbound_group_session_id",
    "_olm_outbound_group_session_id_length",
    "_olm_outbound_group_session_key",
    "_olm_outbound_group_session_key_length",
    "_olm_outbound_group_session_last_error",
    "_olm_outbound_group_session_message_index",
    "_olm_outbound_group_session_size",
    "_olm_pickle_account",
    "_olm_pickle_account_length",
    "_olm_pickle_inbound_group_session",
    "_olm_pickle_inbound_group_session_length",
    "_olm_pickle_outbound_group_session",
    "_olm_pickle_outbound_group_session_length",
    "_olm_pickle_pk_decryption",
    "_olm_pickle_pk_decryption_length",
    "_olm_pickle_session",
    "_olm_pickle_session_length",
    "_olm_pk_ciphertext_length",
    "_olm_pk_decrypt",
    "_olm_pk_decryption",
    "_olm_pk_decryption_last_error",
    "_olm_pk_decryption_size",
    "_olm_pk_encrypt",
    "_olm_pk_encrypt_random_length",
    "_olm_pk_encryption",
    "_olm_pk_encryption_last_error",
    "_olm_pk_encryption_set_recipient_key",
    "_olm_pk_encryption_size",
    "_olm_pk_get_private_key",
    "_olm_pk_key_from_private",
    "_olm_pk_key_length",
    "_olm_pk_mac_length",
    "_olm_pk_max_plaintext_length",
    "_olm_pk_private_key_length",
    "_olm_pk_sign",
    "_olm_pk_signature_length",
    "_olm_pk_signing",
    "_olm_pk_signing_key_from_seed",
    "_olm_pk_signing_last_error",
    "_olm_pk_signing_public_key_length",
    "_olm_pk_signing_seed_length",
    "_olm_pk_signing_size",
    "_olm_remove_one_time_keys",
    "_olm_sas",
    "_olm_sas_calculate_mac",
    "_olm_sas_calculate_mac_long_kdf",
    "_olm_sas_generate_bytes",
    "_olm_sas_get_pubkey",
    "_olm_sas_is_their_key_set",
    "_olm_sas_last_error",
    "_olm_sas_mac_length",
    "_olm_sas_pubkey_length",
    "_olm_sas_set_their_key",
    "_olm_sas_size",
    "_olm_session",
    "_olm_session_describe",
    "_olm_session_has_received_message",
    "_olm_session_id",
    "_olm_session_id_length",
    "_olm_session_last_error",
    "_olm_session_size",
    "_olm_sha256",
    "_olm_sha256_length",
    "_olm_unpickle_account",
    "_olm_unpickle_inbound_group_session",
    "_olm_unpickle_outbound_group_session",
    "_olm_unpickle_pk_decryption",
    "_olm_unpickle_session",
    "_olm_utility",
    "_olm_utility_last_error",
    "_olm_utility_size",

    "_OBJC_CLASS_\$_PSYMarsXLog",

    "_OBJC_CLASS_\$_Reachability",

    "_OBJC_CLASS_\$_RTCAudioTrack",
    "_OBJC_CLASS_\$_RTCCameraVideoCapturer",
    "_OBJC_CLASS_\$_RTCCertificate",
    "_OBJC_CLASS_\$_RTCConfiguration",
    "_OBJC_CLASS_\$_RTCDataBuffer",
    "_OBJC_CLASS_\$_RTCDataChannelConfiguration",
    "_OBJC_CLASS_\$_RTCDefaultVideoDecoderFactory",
    "_OBJC_CLASS_\$_RTCDefaultVideoEncoderFactory",
    "_OBJC_CLASS_\$_RTCIceCandidate",
    "_OBJC_CLASS_\$_RTCIceServer",
    "_OBJC_CLASS_\$_RTCMediaConstraints",
    "_OBJC_CLASS_\$_RTCMediaStream",
    "_OBJC_CLASS_\$_RTCPeerConnectionFactory",
    "_OBJC_CLASS_\$_RTCRtpCodecParameters",
    "_OBJC_CLASS_\$_RTCRtpEncodingParameters",
    "_OBJC_CLASS_\$_RTCRtpHeaderExtension",
    "_OBJC_CLASS_\$_RTCRtpReceiver",
    "_OBJC_CLASS_\$_RTCRtpSender",
    "_OBJC_CLASS_\$_RTCRtpTransceiver",
    "_OBJC_CLASS_\$_RTCRtpTransceiverInit",
    "_OBJC_CLASS_\$_RTCSessionDescription",
    "_OBJC_CLASS_\$_RTCVideoTrack",
    "_RTCCleanupSSL",
    "_RTCInitFieldTrialDictionary",
    "_RTCInitializeSSL",
    "_RTCSetMinDebugLogLevel",
    "_RTCSetupInternalTracer",
    "_RTCShutdownInternalTracer",
    "_kRTCMediaStreamTrackKindAudio",
    "_kRTCMediaStreamTrackKindVideo",

    "_OBJC_CLASS_\$_SEGAnalytics",
    "_OBJC_CLASS_\$_SEGAnalyticsConfiguration",

    "_OBJC_CLASS_\$_SentryBreadcrumb",
    "_OBJC_CLASS_\$_SentryDependencyContainer",
    "_OBJC_CLASS_\$_SentryEnvelope",
    "_OBJC_CLASS_\$_SentryEnvelopeHeader",
    "_OBJC_CLASS_\$_SentryEnvelopeItem",
    "_OBJC_CLASS_\$_SentryEvent",
    "_OBJC_CLASS_\$_SentryException",
    "_OBJC_CLASS_\$_SentryMechanism",
    "_OBJC_CLASS_\$_SentrySDK",
    "_sentrycrash_async_backtrace_decref",
    "_sentrycrashsc_initWithBacktrace",

    "_OBJC_CLASS_\$__TtC13SocketWrapper19ClientSocketWrapper",
    "_OBJC_CLASS_\$__TtC13SocketWrapper27ServerSocketListenerWrapper",

    "_OBJC_CLASS_\$_SSZipArchive",

    "_OBJC_CLASS_\$_IValueWrapper",
    "_OBJC_CLASS_\$_Tensor",
    "_OBJC_CLASS_\$_TorchModule",

    // app.cash.molecule:molecule-runtime-iosarm64:0.7.0
    "_kfun:app.cash.molecule#launchMolecule__at__kotlinx.coroutines.CoroutineScope(app.cash.molecule.RecompositionClock;kotlin.Function0<0:0>){0§<kotlin.Any?>}kotlinx.coroutines.flow.StateFlow<0:0>",
    "_kfun:app.cash.molecule#launchMolecule__at__kotlinx.coroutines.CoroutineScope(app.cash.molecule.RecompositionClock;kotlin.Function1<0:0,kotlin.Unit>;kotlin.Function0<0:0>){0§<kotlin.Any?>}",
    "_kfun:app.cash.molecule#moleculeFlow(app.cash.molecule.RecompositionClock;kotlin.Function0<0:0>){0§<kotlin.Any?>}kotlinx.coroutines.flow.Flow<0:0>",

    // app.cash.redwood:redwood-layout-compose-iosarm64:0.2.1
    "_kfun:app.cash.redwood.layout.compose#Column(app.cash.redwood.layout.api.Constraint;app.cash.redwood.layout.api.Constraint;app.cash.redwood.layout.api.Padding;app.cash.redwood.layout.api.Overflow;app.cash.redwood.layout.api.CrossAxisAlignment;app.cash.redwood.layout.api.MainAxisAlignment;app.cash.redwood.LayoutModifier;kotlin.Function1<app.cash.redwood.layout.compose.ColumnScope,kotlin.Unit>){}",
    "_kfun:app.cash.redwood.layout.compose#Row(app.cash.redwood.layout.api.Constraint;app.cash.redwood.layout.api.Constraint;app.cash.redwood.layout.api.Padding;app.cash.redwood.layout.api.Overflow;app.cash.redwood.layout.api.MainAxisAlignment;app.cash.redwood.layout.api.CrossAxisAlignment;app.cash.redwood.LayoutModifier;kotlin.Function1<app.cash.redwood.layout.compose.RowScope,kotlin.Unit>){}",

    // app.cash.redwood:redwood-treehouse-lazylayout-compose-iosarm64:0.2.1
    "_kfun:app.cash.redwood.treehouse.lazylayout.compose#LazyColumn(kotlin.collections.List<app.cash.redwood.treehouse.lazylayout.api.LazyListIntervalContent>;app.cash.redwood.LayoutModifier){}",
    "_kfun:app.cash.redwood.treehouse.lazylayout.compose#LazyColumn__Skie_DefaultArguments__46(kotlin.collections.List<app.cash.redwood.treehouse.lazylayout.api.LazyListIntervalContent>){}",

    // co.touchlab:sqliter-iosarm64:0.7.1
    "_KonanNeedDebugInfo",
    "__Z19RuntimeAssertFailedPKcS0_",
    "__ZN5konan4freeEPv",
    "__ZN5konan6callocEmm",

    // com.adeo:kviewmodel-compose-iosarm64:0.13
    "_kfun:com.adeo.kviewmodel.compose#ViewModel(kotlin.Function0<0:0>;kotlin.Function1<0:0,kotlin.Unit>){0§<com.adeo.kviewmodel.KViewModel>}",
    "_kfun:com.adeo.kviewmodel.compose#observeAsState__at__kotlinx.coroutines.flow.SharedFlow<0:0>(kotlin.coroutines.CoroutineContext){0§<kotlin.Any?>}androidx.compose.runtime.State<0:0?>",
    "_kfun:com.adeo.kviewmodel.compose#observeAsState__at__kotlinx.coroutines.flow.StateFlow<0:0>(kotlin.coroutines.CoroutineContext){0§<kotlin.Any?>}androidx.compose.runtime.State<0:0>",

    // com.episode6.redux:compose-ios-arm64:1.0.1
    "_kfun:com.episode6.redux.compose#collectAsState__at__com.episode6.redux.StoreFlow<0:0>(kotlin.coroutines.CoroutineContext){0§<kotlin.Any?>}androidx.compose.runtime.State<0:0>",
    "_kfun:com.episode6.redux.compose#collectAsState__at__com.episode6.redux.StoreFlow<0:0>(kotlin.coroutines.CoroutineContext;kotlin.Function1<0:0,0:1>){0§<kotlin.Any?>;1§<kotlin.Any?>}androidx.compose.runtime.State<0:1>",
)
