use_frameworks!

install! 'cocoapods', :deterministic_uuids => false

targets = {
  "iOS" => { "platform" => :ios, "version" => "12.4", "tests" => true },
  # This is the iOS app for the watchOS one. WatchOS is configured separately
  "watchOS" => { "platform" => :ios, "version" => "12.4", "tests" => false },
  "watchOS_WatchKit_App" => { "platform" => :watchos, "version" => "8.0", "tests" => false },
  "watchOS_WatchKit_Extension" => { "platform" => :watchos, "version" => "8.0", "tests" => false },
  "macOS" => { "platform" => :osx, "version" => "11.0", "tests" => true },
  "tvOS" => { "platform" => :tvos, "version" => "12.4", "tests" => true },
}

types = {
  "dynamic" => "Dynamic",
  "static" => "Static",
}

targets.each do |key, value|
  types.each do |type, suffix|
    target "SwiftLinkExample_#{key}_#{suffix}" do
      platform value["platform"], value["version"]

      pod "ExampleKit_#{suffix}", :path => "../#{type}"

      if value["tests"]
        target "SwiftLinkExample_#{key}_#{suffix}_Tests" do
          inherit! :search_paths
        end
      end
    end
  end
end
