package co.touchlab.skie.swiftmodel.callable.property

import co.touchlab.skie.swiftmodel.callable.MutableKotlinCallableMemberSwiftModel

interface MutableKotlinPropertySwiftModel : KotlinPropertySwiftModel, MutableKotlinCallableMemberSwiftModel
