use_frameworks!

install! 'cocoapods', :deterministic_uuids => false

targets = {
  "iOS" => { "platform" => :ios, "version" => "12.4" },
  # This is the iOS app for the watchOS one. WatchOS is configured separately
  "watchOS" => { "platform" => :ios, "version" => "12.4" },
  "watchOS_WatchKit_App" => { "platform" => :watchos, "version" => "8.0" },
  "watchOS_WatchKit_Extension" => { "platform" => :watchos, "version" => "8.0" },
  "macOS" => { "platform" => :osx, "version" => "11.0" },
  "tvOS" => { "platform" => :tvos, "version" => "12.4" },
}

types = {
  "dynamic" => "Dynamic",
  "static" => "Static",
}

targets.each do |key, value|
  types.each do |type, suffix|
    target "SwiktExample_#{key}_#{suffix}" do
      platform value["platform"], value["version"]

      pod "ExampleKit_#{suffix}", :path => "../#{type}"
    end
  end
end
